### ISSUE TITLE
Should not change the points passed by constructor

### ISSUE THREAD

**Issue by chinkuanyeh** [kangax/fabric.js#1022]
In the fabric.js source code (for Polyline and Polygone class):
![image](https://f.cloud.github.com/assets/1196125/1653216/930e09fa-5b2e-11e3-82f0-6bdc2017c856.png)

I think Fabric.js should not change the points passed by constructor. Because this is not an ideal design for future extension. For example, the x, y values of points may be meaningful for some application and they needs to save and restore. And fabric.js may provide additional functions to modify points on the fly in the future.

Anyway. Fabric.js is great. Thank you and sorry for my poor English. 

                                                          Matthew Yeh

**Comment by asturur** [comment]
@kangax @Kienz we may consider adding an 
originalPoints array that returns the points passed to constructor
a actualPoints array that returns the points on canvas ( including rotation scaling skewing etc etc )
i mark as a possible feature. The issue itself is based on old code.

**Comment by kangax** [comment]
@asturur good idea

**Comment by Eskatrem** [comment]
I stumbled on that as well, while running the code:

    var a = 100;
    var b = 200;
    var xMin = 10;
    var yMax = 310;
    var aPoint = {x:xMin,y:yMax};
    var bPoint = {x:xMin+b,y:yMax};
    var cPoint = {x:xMin,y:yMax-a};
    var poly1 = new fabric.Polyline([aPoint,bPoint,cPoint,aPoint], {fill: 'white', stroke:'red'});

This code change the value of aPoint and the Polyline is not displayed the way I intend. One way to fix it is the following:

    var poly1 = new fabric.Polyline([aPoint,bPoint,cPoint,{x:xMin,y:yMax};], {fill: 'white', stroke:'red'});

It now works but it doesn't feel natural. 

Since @chinkuanyeh has indicated what change to make in the code to avoid this behavior, I can do it you think it will help fabric.js

**Comment by asturur** [comment]
@eskatrem your issue us not related to that.
your problem is that you are using a polyline to close on itself using twice aPoint.

i know that use a polygon is not the right answer, but make a clone of aPoint and you should be fine.

is not stated in the docs that you have to use distinct objects as points, but is not innatural to do that.

**Comment by Eskatrem** [comment]
Yes @asturur I am making a wrapper around Polyline to clone the input points. Thanks.

**Comment by asturur** [comment]
We are not changing the point from constructor anymore. We added a canvas translation similar to Path class.
I would close this.
