### ISSUE TITLE
Programmatically created group doesn't retain correct position/size/rotation

### ISSUE THREAD

**Issue by hybra** [kangax/fabric.js#1065]
Hello

I set up a fiddle to demonstrate the problem:

http://jsfiddle.net/ZSk74/

click on "draw" button then drag the group somewhere else, then deselect it by clicking on the canvas.

Edit:
it also appear to repeat scale and rotate, besides changing position.

Update: I noticed that dragging the group to (0,0) of canvas then clicking to deselect looks like it's working, so there's probably some relation to the distance from the top:0, left:0 position

**Comment by asturur** [comment]
The situation changed with latest version.
I see a different problem.
After deselecting the group and reselecting it, the control box moves and  the circles stay put.
http://jsfiddle.net/ZSk74/2/

**Comment by KJTsanaktsidis** [comment]
@asturur with regards to your fiddle...

The reason your group doesn't seem to correctly activate with the call to `setActiveGroup` is simply that you need a `renderAll`. It activates perfectly.

When the group is deselected, `destroy` is called on the group and so the circles have their coordinates restored to their original, canvas-relative values. Clearly, we don't want the canvas destroying a group it did not create.

Your fiddle works fine if you call `setActiveObject` on the group, rather than `setActiveGroup`. The fix for this should either be-
* Document that `setActiveGroup` is really only for making a selection group, and that for scenarios like the one in your fiddle, `setActiveObject` should be used. Ideally `setActiveGroup` would be made private, only to be called by `canvas_grouping.mixin.js`.
* Have the canvas remember whether or not it created the currently active group, and only destroy it if it did.

**Comment by asturur** [comment]
i was refreshing old issue to see if some update fixed the abandoned issue.

i never understood what the setactivegroup.is supposed to do :)

So if it force fabric that to tink that this group is created by user selection, what is happening here is perfectly normal and we can just close this old issue.
