### ISSUE TITLE
Prevent pattern from scaling when object scales

### ISSUE THREAD

**Issue by fmahannah** [kangax/fabric.js#1130]
I can't figure out a way to apply a pattern repeat fill to an object or shape and have it not scale when the object is scaled.

Even if I recreate the object and apply the pattern again it gets distorted if the object is scaled at all or on an ellipse that is wider than it is tall or vice versa.

Surely there is a way to apply a repeat pattern fill to a shape and have it applied after any transformations?

Any ideas or example appreciated, project is being held up by this one key issue

Thanks
##

**Comment by sompylasar** [comment]
Here's the solution:
http://stackoverflow.com/questions/19246791/pattern-quality-is-missing-when-object-is-scaled-in-fabricjs/19515190#19515190

**Comment by asturur** [comment]
Sadly this solution won't work.

Modifing width and height of an object is not scaling the object.
Take a complex path, modify width and height properties and you will get exactly the same path.

Width and height are a consequence of the object and not the parameters that define it.
(exception made for rect)

**Comment by sompylasar** [comment]
Oh, I understand now. I used this solution for rectangles only.

Later I got another solution because I needed a contiguous pattern across
multiple objects. I used an object that fills the whole canvas, filled it
with a pattern and clipped it with my set of objects (each with zero
opacity). Though I only used rectangles, too, I know that clipping with
arbitrary shapes is possible.

**Comment by asturur** [comment]
one solution would be restoring the scale factor of the canvas transofrmation before filling. same technic used for ellipse border. ( i m guessing here )

**Comment by asturur** [comment]
merge with issue #3499
