### ISSUE TITLE
easeOutElastic - NaN result

### ISSUE THREAD

**Issue by cimak** [kangax/fabric.js#1271]
fabric.util.ease['easeOutElastic'] returns NaN for these arguments: 2, 1, 0, 550
// 0 is the problem

**Comment by asturur** [comment]
i resumed this old issue. I fixed the normalize function where there was a Math.sin(0/0).
The point is that the original fiddle for the issue is not supposed to animate animore after the first animation. After animating to 4,33, the next animation start from that point and is not going to move.
Effectively the bug was there, since after the first animation they were returning NaN.

new http://jsfiddle.net/JvA8v/4/
old http://jsfiddle.net/JvA8v/5/

They are both working if the animation start and end to a different point.
