### ISSUE TITLE
Groups fail to have controls when created as a result of an event in an AMD environment.

### ISSUE THREAD

**Issue by zenimpulse** [kangax/fabric.js#1334]
I'm currently trying to use Fabric in a AMD web app using Require and Knockout, and when I try to create groups based on API data and then load them into the canvas, they appear, but I can't select or move them around. The selection event never even fires.

This is the event binding that's leading to the creation of groups:
```JavaScript
DataEvents.loadPage.add(function(page){
                    var result = PageViewModel.harvestPageItems(page.pageItems);
                    PageViewModel.pageData(result);
                    for(var i = 0; i < result.length; i++) {
                        var items = result[i].promo.product.productItems;
                        if(items.length !== 0) {
                            for(var x = 0; x < items.length; x++) {
                                var group = CanvasHelper.buildTestItem(items[x].sku.sKU_SHORT_DESC);
                                PageViewModel.canvas.add(group);
                                PageViewModel.canvas.selection = true;
                            }
                        }
                    }
```

The CanvasHelper function that creates the groups is this:
```JavaScript
buildTestItem: function(description) {
                var rect = new fabric.Rect({
                    width: 150, 
                    height: 150, 
                    fill: '#292929'
                });
                var label = new fabric.Text(description, {
                    fontSize: 16,
                    width: 150,
                    fontFamily: 'Helvetica',
                    fontWeight: 'bold',
                    fill: '#ffffff'
                });
                var group = new fabric.Group([rect, label], {
                    left: 10,
                    top: 10,
                    selectable: true,
                    hasControls: true,
                    hasRotatingPoint: false
                });
                return group;
            }
```

**Comment by zeorin** [comment]
+1 for me, too.

However, I think I've fixed this, or at the very least found a work-around. I am using Ampersand.js (which is based on Backbone.js).

Essentially, a view is rendering a template in my app. That template is a `canvas` element (**i.e. it's the only element in the template**), and directly after rendering I am creating a new Fabric instance on that `canvas` element.

What's happening is the following: `fabric.Canvas` constructor runs *before the rendered template has actually been added to the DOM*. This is not Fabric's fault. It has to do with how browser event queues work. Even though the MVC app has sent the instruction for the template to be added to the DOM, this hasn't actually happened yet--instead the browser has only added that instruction to the event queue. See the following links for more information:

http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful#answer-4575011
http://ejohn.org/blog/how-javascript-timers-work/

The `fabric.Canvas` constructor tries to create a second canvas on top of the first. The upper canvas is your interactivity layer. To add it, it first tries to wrap the lower (original) canvas in a wrapper container div. However, it only does this if it can find the parent node of the lower canvas. Since the browser hasn't yet actually added the `canvas` element to the DOM, there is no parent node, and the `fabric.Canvas` constructor silently aborts the construction of the interactivity layer.

My solution was to use a `setTimeout(function () { ... }, 0)` wrapper around the `fabric.Canvas` constructor call. However, I also tested adding a `div` around the `canvas` element in my template instead.

Both worked.

One might be tempted to bake the `setTimeout(function () { ... }, 0)` solution into the `fabric.Canvas` constructor. I would advise against that, as it is difficult to know exactly how many event queues one would have 'escape' before we're sure that the `canvas` element has been added to the DOM (i.e. wrapping the function in only one `setTimeout(function () { ... }, 0)` call may not be enough--I think this will vary per MVC framework).

I would not 'fix' this issue, but instead add a note to the docs somewhere about the reason for the behaviour and assume that app developers can figure it out from there. Fabric is not the only framework/code that will run into this problem.

The real solution is for app developers to understand browser event queues.
