### ISSUE TITLE
can not apply filters on image from cross origin

### ISSUE THREAD

**Issue by wajipk** [kangax/fabric.js#1617]
We are using the following code to load images on canvas

` fabric.Image.fromURL(src, function(oImg) { 
			/* other options for images*/`
`				canvas.add(oImg);`
`				canvas.calcOffset();`
`			}`
`		});`

image is loaded successfully on canvas, but when we apply filter on this image it will give a cross origin error. "Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data. " 
i can't understand what is the problem.

Thanks in advance.
@kangax @Kienz

**Comment by Kienz** [comment]
@wajipk The difference is, that the `crossOrigin` in the first examlpe is set before the image is loaded. In the second the attributes is added after the image is loaded. The `crossOrigin` attribute have to be set before the image request started.
```js
var img = document.createElement('img');
// have to be set before `src` attribute is set
img.crossOrigin = 'anonymous';

img.onload = function () {
  console.log('image loaded');
};
img.src = 'http://....';
```

**Comment by mohitv789** [comment]
Hello,

I am working on a web app which has backend in Djangorestframework and frontend in angular. There is a nginx layer for backend only and frontend is served directly through npm start command with proxy-config. My api is running on localhost:8000 and frontend on localhost:4200.
I am fetching the model data from backend which has image as one of the field. This image is used in the component and loaded in canvas, I have custom functions defined for applying filters , cropping and some other functions. I am able to successfully load the image in canvas with or without --> image.crossOrigin = 'Anonymous' (during image loading using function mentioned in notes); since I am using django-cors-headers. 
But when I apply some image manipulation functions (function mentioned in notes) , then I am getting error : "ERROR DOMException: The operation is insecure.". I have whitelisted the frontend in Djangorestframework API server.

--> I have some additional functions defined as well but I dont know how to show them here without uploading full project on github ( it is private repo currently )

Notes for codes:
```
addImageOnCanvas(url:string):void{
  if (url) {
    fabric.Image.fromURL(url, (image: any) => {
      let scaleXFactor = (this.size.width - 20)/image.width;
      let scaleYFactor = scaleXFactor;
      image.set({
        left: 10,
        top: 10,
        scaleX: scaleXFactor,
        scaleY: scaleYFactor,
        angle: 0,
        cornersize: 10,
        hasRotatingPoint: true
      });
      // image.crossOrigin = 'Anonymous';
      this.extend(image, this.randomId());
      this.canvas.add(image);
      this.selectItemAfterAdded(image);
    });
  }

applyFilterOnSingle(filterProps:any):void{
  if(this.activeObjectType === 'image'){
    this.activeObject.filters = this.generateFilterArray(filterProps);
    this.activeObject.applyFilters();
    this.canvas.renderAll();
  }
}

generateFilterArray(filterProps:any):any[]{
  let filterArray = [];
  if(filterProps.brightness !== 0){
    filterArray.push(
      new fabric.Image.filters.Brightness({
        brightness:filterProps.brightness
      }
    ));
  }
  if(filterProps.contrast !== 0){
    filterArray.push(
      new fabric.Image.filters.Contrast({
        contrast:filterProps.contrast
      }
    ));
  }
  // and so on
  return filterArray;
}
```

Any help would be greatly appreciated.

Thank You :-)

**Comment by mohitv789** [comment]
No Worries , it got resolved by this thread action point : https://github.com/fabricjs/fabric.js/issues/6397
