### ISSUE TITLE
toDataURL affected by the canvas zoom level

### ISSUE THREAD

**Issue by ggmendez** [kangax/fabric.js#1811]
Apparently, when the canvas has been zoomed in or out, the toDataURL  method clips the image data.

**Comment by jrett** [comment]
I'm not sure if this is related or if I should post a separate issue, but there is what I'm observing...
When I have setZoom to something other than 1, all works well, except if I have a clipTo defined on the canvas. This clipTo region does not take the current setZoom value into consideration and are clipped incorrectly. I don't know if its intended that the user update the clipping region or if this is a bug.
I'm not sure, but this sounds like it could also be the root cause of the issue ggmendez is reporting.

**Comment by xronos-i-am** [comment]
This works for me: https://github.com/xronos-i-am/fabric.js/commit/ae0300f5d0dbe3a76ca2cc76ac3005623fee0997 
Should be tested more

**Comment by asturur** [comment]
i think that if do not want to have the zoom affect the canvas, setting the viewport to identity before dataurling is fine ( and restoring later ). While if we do not have the feature, tiling a big canvas would be impossible.
The viewport does zoom and panning.
