### ISSUE TITLE
Transform only a select area inside a path with multiple lines.

### ISSUE THREAD

**Issue by guilhermecruzpleimo** [kangax/fabric.js#1939]
My '.ai' image is a tracing image, so i have only 1 path. I had serialized my SVG to canvas and i wan't to select some of the anchor points to transform an area.

In this case i have a pictogram , and for example i want to resize only the hands (but the hands aren't a individual layer/object or path) there is a way to transform a 'selected area'?

**Comment by asturur** [comment]
Your problem is very generic and is more suited for google groups or stack overflow.
As of now fabricjs does not  handle path in a way you can divide them in sub objects. ( even if this is not   really an impossible task ) so your solution can come from fabricjs or from pre processing the file before loading it, splitting in more paths

I indeed suggest you to divide your path commands in different paths, aligning them with M commands.

Do you have an example file?

Better you ask somewhere more generic, sorry.
