### ISSUE TITLE
Group._setObjectPosition does not fire object:modified events after updating objects in group

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#1952]
When a group is destroyed, `_restoreObjectState` updates all Objects that were in the group with new angle, scale and location values. It needs to fire the `object:modified` event for each object when new values are set on it.

### Suggested fix
Fix is as simple as adding the following line at the end of the `_setObjectPosition` function in `group.class.js`:
```
this.canvas.fire('object:modified', { target: object });
```

**Comment by kangax** [comment]
But the objects are not modified at that moment, as far as scale/rotation/position :) The only thing that's changed about them is presence in a group.

**Comment by jafferhaider** [comment]
I'm concerned about the following code:
```
object.set({
        angle: object.getAngle() + this.getAngle(),
        left: center.x + rotated.left,
        top: center.y + rotated.top,
        scaleX: object.get('scaleX') * this.get('scaleX'),
        scaleY: object.get('scaleY') * this.get('scaleY')
      });
```
I believe this is applying non-delegated properties on objects in the group when it is destroyed. Visually objects don't change but values inside objects change because they aren't effected by the group anymore.

I came across this issue while wiring up Fabric with an MVC layer ... my model representation (for each Fabric Object) went out of date after a group was destroyed because this code updated the Fabric Object (the view) but did not fire a object:modified event.

Does this make sense?

**Comment by kangax** [comment]
I understand. Perhaps you can observe "selection:cleared" event then?

The reason I'd hesitate to add "object:modified" in this case is exactly because nothing changes visually. Imagine you have a state manager of some sort; say, undo/redo implementation using command pattern. You're observing "object:modified" event to create new commands and add them to the stack. If we fire "object:modified" event in this case, you'll essentially end up with a state in a stack that doesn't represent any modification (you click "back/undo" and nothing happens; I hope it makes sense). This is why in my app, group creation/destruction is represented as a separate type of command (also added to stack) so that when you undo, modification-related commands perform modifications (moved, scaled, rotated), while group-related commands perform group creation/destruction.

**Comment by jafferhaider** [comment]
Ah OK, I'll go with that approach. Thanks!

**Comment by jafferhaider** [comment]
For anyone reading this discussion after the fact, the event that you'd need to use to know when a group is cleared/destroyed is `before:selection:cleared`, and not the `selection:cleared`, because the latter does not pass the `target` to its handler.
