### ISSUE TITLE
Canvas.renderAll end of process.

### ISSUE THREAD

**Issue by divyamzn** [kangax/fabric.js#1969]
How to know if canvas.renderAll() has rendered all the objects when called from loadFromJSON method? We have a requirement to show busy loading icon till all the objects are loaded on canvas as image loading takes some time.

**Comment by asturur** [comment]
renderAll is a syncronous function.

Your problem is to know when all objects are finished loading and so you know when you can call renderAll().

This problem is in the list of fixes for 1.5.0, is the issue: #935 , even if the title does not match, the problem is that loadFromJSON does not wait for the pattern to finish loading.

**Comment by kangax** [comment]
As @asturur said, `renderAll()` is synchornous, so it's finished whenever the method is finished.

**Comment by divyamzn** [comment]
My issue here is ... how to know if the images in the JSON have finished loading when called from loadFromJSON method so that I can show a busy loading icon on the canvas till the image gets rendered.

**Comment by asturur** [comment]
Is the next thing to solve.

**Comment by serkyen** [comment]
Is this solved?

**Comment by asturur** [comment]
well i think so, loadFromJson as a callback, that wait for everything
