### ISSUE TITLE
Feature request: Create rotated selection group when select same angle objects

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2080]
SITUATION:
Select multi-objects whose angles are same, then, a selection group is created.

NOW:
The angle of the selection group is always zero, even though the angle of the grouped objects is not zero.

I WISH:
The angle of the selection group is same as the angle of the grouped objects.

![test](https://cloud.githubusercontent.com/assets/11169954/6991835/9ab0298e-dae6-11e4-86a4-17e4f4a29cd4.png)
##

**Comment by kangax** [comment]
Does any editing tool work like this? As far as I rmember Photoshop, for example, does what we do too.

**Comment by sapics** [comment]
Illustator has the feature which I wish.

**Comment by asturur** [comment]
please take in account general transform matrix and complex situation. angle is our object.angle, while rotation on screen is a mix of factors. you will see that there will be a rotated square with a perfectly not rotated selection box, because the angles is 0 but transformMatrix is ( 1, cos(), - cos() 1) .....  transformMatrix are not always invertivble or decomponible.
while this may be sound reasonable, try to extend the concept to scale and translate and you will see that lot of complication comes, and for which good?

it may be interesting maybe to add a getAngle(true) method where  we calculate total rotation of the object considering group parents

**Comment by sapics** [comment]
@asturur　I understand that it is difficult to do and make complexity for creating rotated group.
For me, this feature looks usual operation.
And I guess that when #2073 is done, this feature would be easier.

**Comment by kangax** [comment]
@sapics can you give an example of when it's useful?

**Comment by sapics** [comment]
@kangax For example, for hand editing.
1. Rotate selection group. [23 degree]
2. Unselect.
...
3. Reselect objects.
4. Rotate group 67 degree (which makes 90 degree to objects) by hand is very difficult.
   But if group is has 23 degree already, additional 67 degree is easy, if there are rotation snap feature.

I'm sorry, my bad English.

**Comment by kangax** [comment]
I see what you mean. I think it's a pretty specific use case, so perhaps a "possible feature"

**Comment by asturur** [comment]
I do not think we can implement this feature with a reasonable effort.
Is not just rotating back the object before grouping.
