### ISSUE TITLE
Can't select object after zoom on mobile

### ISSUE THREAD

**Issue by mina-thomas** [kangax/fabric.js#2111]
##

**Comment by mina-thomas** [comment]
I can't select any object if make a zoom in the mobile page

**Comment by kangax** [comment]
We need some sort of reproducible test case and more information — which device? which browser?

**Comment by mina-thomas** [comment]
my device is nexus 5, chrome browser
I think you can reproduce it, if you visit www.fabricjs.com, you will be able to select all objects
but if you make page zoom, you will not be able to select

**Comment by kangax** [comment]
Ok, I'll reopen for now. Perhaps someone with nexus will be able to reproduce.

**Comment by mina-thomas** [comment]
I think it's not nexus problem. It's touche devices problem

**Comment by X4V18** [comment]
I have the same issue with Galaxy S5 (SM-G900F). It is not a nexus problem but a scale problem (Webview or Cordova?). To reproduce to issue it is quite simple,  just create a big canvas (bigger than screen width) then add somes elements on it (rect, circle, ...) and set zoom property on it (0.5 for example). If you add a square at x:100 and y:100 and set the scale to 0.5, the element will be located at (50,50) and no more at (100,100) so the problem is the mouse event is handle at incorrect location.
Sorry for my bad english, I try to explain the best I can. If something is not clear don't hesitate to ask some details more.

**Comment by X4V18** [comment]
I have found a workaround, use the tranform property or duplicate the canvas. The two solution is exposed in [my post here](https://stackoverflow.com/questions/30862356/fabric-js-resize-canvas-to-fit-screen).
