### ISSUE TITLE
1.5 regression: iText cursor and selection ignores transform

### ISSUE THREAD

**Issue by tjunnone** [kangax/fabric.js#2122]
Fabric.js 1.5.0 renders the cursor and selection for the below IText object incorrectly, ignoring the transformation that is applied to the text. Version 1.4.13 renders both correctly (the bounding box is off in both versions due to issue #1520)

```javascript
var canvas = new fabric.Canvas('c');
var iText = new fabric.IText("Hello world", {
    transformMatrix: [1, 0.5, -1, 0.5, 0, 0],
    left: 100,
    top: 100
});
canvas.add(iText);
```
![itext-transform-bug](https://cloud.githubusercontent.com/assets/923483/7194770/617e42da-e483-11e4-8d5c-40b004ec85dd.png)

**Comment by asturur** [comment]
we are working on transformMatrix general support.

Transform Matrix is not supported with interactivity. Almost every function other than SVG break down if you apply a general transformMatrix on an object outside a pathgroup.

Is still a missing feature. The fact that from 1.5.0 to 1.4.13 they look differnt is because the cursor and selection have been moved to uppercanvas for performance reason.

**Comment by asturur** [comment]
If you want is easily fixable.
You can add after this line
https://github.com/kangax/fabric.js/blob/master/src/shapes/itext.class.js#L329 
this.transformMatrix && ctx.transform.apply(ctx, this.transformMatrix);
or after line 330.

I prefer to work on the proper fix, but if you need for some particular reason to have it working immediately this could be a solution.
