### ISSUE TITLE
fabric.js online demos do not support Chrome emulation?

### ISSUE THREAD

**Issue by grinchak** [kangax/fabric.js#2133]
For example, this online fabric demo  http://fabricjs.com/touch-events/ can only select and deselect fabric object with mouse click while under Chrome emulators. Events console shows dragging, but no object dragging had occurred. Can't interact with control handles to scale, rotate or move.
![capture](https://cloud.githubusercontent.com/assets/12039081/7239244/2350d658-e75d-11e4-9e37-51f9dbb9f2d1.JPG)

**Comment by kangax** [comment]
I'm not sure why this happens. Need to investigate, but since this is not really a bug or a feature, we probably won't have time to look into it. If you can find out what happens, please feel free to leave a comment; perhaps it will be helpful to someone. In case this behavior is indicative of a real issue with touch events in Fabric, we'll certainly reopen this, but gotta have more details.
