### ISSUE TITLE
Unit test error in Google Chrome

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2157]
This issue is just a report of unit test error in Google Chrome 64bit, Windows 8.1.

Second error about **fabric.Object:getBoundingRect** would be negligibly small.
Last error about **fabric.Pattern:toObject**, I do not know which is acceptable **Expected** or **Result**.

![ws000019](https://cloud.githubusercontent.com/assets/11169954/7363276/bd722204-edb2-11e4-9c19-8ae3b3da385c.png)

![ws000020](https://cloud.githubusercontent.com/assets/11169954/7363278/c120b0a0-edb2-11e4-9712-557e68d0c544.png)

**Comment by kangax** [comment]
I fixed the pattern one. Not sure what's going on with bounding rect. 

@asturur @sapics mind taking a look when you get a chance?

**Comment by asturur** [comment]
Bounding rect act on oCoords that make wild use of cos, sen, Math functions.
I do not know if it could happen that some operation made witth floats get crazy result.
You know those 4.0 + 3.0 = 6.9999999999999999999999999999999999999 sometimes...
I would not bother, is very near to 0.


The to SVG test that is failing is because i never noticed it before today. is a test that do no run on node.js. i'll fix it.

**Comment by kangax** [comment]
Thanks

**Comment by sapics** [comment]
@kangax I checked current kangax/master pass the unit test Pattern.toObject and IText:toSVG in Chrome.

Unit test error for getBoundingRect is ignorable small.
For removing this error, it would be ok by fixing like (value).toFixed(12 or 13), isn't it?
If it is ok, i will fix it.

**Comment by kangax** [comment]
That's probably ok, yes. Please send a PR.
