### ISSUE TITLE
Using globalCompositeOperation in group

### ISSUE THREAD

**Issue by webmak** [kangax/fabric.js#2180]
I am trying to create groupe using fabricjs
var group = new fabric.Group(
   [ circle, this.callerObject ],
   {globalCompositeOperation:'xor'}
);
But which globalCompositeOperation I have not set it is not working it always give the same result. I can make it using clear canvas, but I want to know, can I do it using native fabricjs methods?

**Comment by webmak** [comment]
I find solution myself)) to make it work need add globalCompositeOperation to the second object. 
Sorry to take your time

**Comment by asturur** [comment]
Group does not have same render method as other objects.
Does not have shadow, globalCompositeOperation, globalAlpha.

GlobalAlpha gets emulated multiplying the group alpha with the single object alpha.
It does not have renderFill nor renderStroke.

but it has transforMatrix and clipTo method

I do not know if it is by design or by accident.

I do not even know if it can be easily supported.
The object get drawn object by object. XOR means that it get rendered the part that is not covered by more than one object.
This happen object over background.

When you do at group level, this would happen object by object, one object gets drawn, and it becomes background. Then other object get drawn and is XORED with background.

You will have an effect that is strange, is not the group XORED with background but every object is XORED with Background that is changing every object that gets drawn.

So at the end, putting XOR to every object in the group you obtain the same effect.

To emulate XOR of a group as a single object we should first draw the group on separate canvas with source-over, and then XOR on the canvas.

I hope it helps.


What do you say @kangax?

**Comment by webmak** [comment]
but it have new problem)) this is work across all images) now I'll try to find better solution

**Comment by webmak** [comment]
"To emulate XOR of a group as a single object we should first draw the group on separate canvas with source-over, and then XOR on the canvas."
I am shure it is not if it work in groupe it mast work for all, I hope

**Comment by webmak** [comment]
writeInCircle: function(){
        if(!this.callerObject){
            return;
        }
        this.callerObject.setOriginToCenter && this.callerObject.setOriginToCenter();
        var radius = parseInt(Math.sqrt(
            Math.pow(this.callerObject.width*this.callerObject.scaleX,2)+
            Math.pow(this.callerObject.height*this.callerObject.scaleY,2)
        )/2*(1+this.DEFAULT_PADDING));
        var circle = new fabric.Circle({
            radius: radius,
            fill: '#eef',
            originX: 'center',
            originY: 'center',
            top: this.callerObject.top,
            left: this.callerObject.left
        });
        this.callerObject.set('globalCompositeOperation','xor');
        this.mainCanvas.remove(this.callerObject);
        var group = new fabric.Group([ circle, this.callerObject ]);
        this.mainCanvas.add(group);
        this.callerObject.setCenterToOrigin && this.callerObject.setCenterToOrigin();
    },

**Comment by webmak** [comment]
sorry but I do not understand how to markup code(

**Comment by asturur** [comment]
You should at least show an image of what are you trying to obtains.
Otherways is so difficult to help.

**Comment by webmak** [comment]
![2015-05-08 18 22 32](https://cloud.githubusercontent.com/assets/10329044/7539377/40f82d72-f5af-11e4-9b01-8c37dfad8e97.png)

**Comment by webmak** [comment]
I can override it, but I hope it can work with out it

**Comment by asturur** [comment]
I cannot understand what you need from that picture.
I see a car, and over a circle with badbatsumaru transparent inside.

What should happen? can you make an example?

**Comment by webmak** [comment]
http://youtu.be/WwkkrwVj568

**Comment by webmak** [comment]
firs questions was how to make xor on the circle, I find solution.
But now new problem it work accross all images.

**Comment by asturur** [comment]
I cannot understand what you want to achieve sorry.

**Comment by webmak** [comment]
No problem. I do not whant to see basic bacgorund accross the circle, I whant to see the car(

**Comment by asturur** [comment]
OK bu the basic background is DRAWN ON CANVAS? or is on the HTML PAGE?

**Comment by webmak** [comment]
basic bacground drow in html, car in canvas

**Comment by asturur** [comment]
It could be easier, depending on app requirements, that you export to "dataurl png" the object that you just transformed in a circle with transparent hole.

Then reload it as a normal image with transparent pixels.

Without knowing in wich order the object are loaded on canvas, is hard to judge if something is going wrong or is just misused.

**Comment by webmak** [comment]
yes I know it) but then I'll need make previous staturs saver the same as in fabricjs( I do not wont to do this.

**Comment by webmak** [comment]
"Without knowing in wich order the object are loaded on canvas, is hard to judge if something is going wrong or is just misused."
There problem in order?
I change indexes for all objects, car index is allways 0

**Comment by asturur** [comment]
It cannot work in this way.
Because car is drawn -> becomes background.
badbatsumaru is drawn or circle is drwan -> car + new object is the new background
circle is drawn and you XOR with mix of car and object, or vice versa.

So a different solution could be:

Make XOR between circle and badbatsumaru, Then draw the picture over them ( index 2 ? ) with globalCompositeOperation equal to destination-out or destination-over.

This could do someting.

If you want just a rouny shape, you can clip the group with a circle using clipTo().

**Comment by webmak** [comment]
It wuld not help(  globalCompositeOperation it seems to work accross all layerd the lower then curren(

**Comment by webmak** [comment]
for this case I have make this, not god but work
1) conver groupe to png
2) hide groupe
3) add new image from groupe png
4) for this image add listener whitch make clone all operations with image to grope
5) whent I need to regroupe elements, I delete image and take image from groupe
with this I have not mutch code)

**Comment by webmak** [comment]
I have refacor my code and make it more clearly and easy.
1) create group with needed
2) copy group withh neede and adding first group converted to data url to this goup
3) delete first groupe
In this way I have recived needed result with out making huge list of code)
