### ISSUE TITLE
Text Pattern issue to add fill color

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#2195]
I have tried to add text pattern and now i want to fill text with color.

Reason: i want to paint my pattern so it will look like i have change the pattern color

But not happening please guide me 

Simple red color works
http://jsfiddle.net/3x8bs/32/

Pattern with color fill (NOT WORKING )
http://jsfiddle.net/3x8bs/31/

Let me know how i can fix the issue

**Comment by asturur** [comment]
Please, this a question for google group or stackoverflow.
We have lot of difficulties to clear issues and find and correct bugs, we cannot handle also this here.
Anyway the problem is that the text can be filled either with color or with a pattern. Not both.
You have to create the pattern with the a function that mix color and pattern.
Please have a look at this demo that a user posted here to file a bug:

https://github.com/kangax/fabric.js/issues/760

in the fiddle linked the pattern is dinamically created. it could help you.
