### ISSUE TITLE
The stroke of object, how to keep its width after being scaled

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#2235]
Current I have tried fabricjs 1.4.13, and I found the stroke of shapes, when we scaled the shape, the stroke scaled as well, stroke is regarded as the border of shape in the app I working on, it not suppose to change, so how to prevent the stroke width from being affected by scaling? 

![2015-05-27 10 55 37](https://cloud.githubusercontent.com/assets/4657101/7839164/86a619ba-04c3-11e5-876c-0f29e6bc75e1.png)

**Comment by asturur** [comment]
you can dinamically change the strokeWidth to desiredWidth/scaleFactor

the problem is that we use ctx.stroke, one method, and you may have different scaling for x and y axis.

consider patching the render functions and move the call ctx.restore between ctx.fill and ctx.restore.

look for example our ellipse class is a deformed circle but has not affected strokeWidth ( if you do not deform it additionally )

**Comment by hellomaya** [comment]
@asturur  thank you! I will try.

**Comment by asturur** [comment]
there is a typo in my post

"move the call ctx.restore between ctx.fill and ctx.stroke"

**Comment by hellomaya** [comment]
@asturur 

I have tried it according to your explanation, and it works, just a small issue now, here is what I have changed, I added ctx.save and ctx.restore in object.render between transform and _render, moved _renderStroke from each objects to object class, so its shared for now, so the context of transform is obsolete from stroke, it did make the stroke always same size whatever the object is scaled or not, I also found that a issue, the controls & borders calculation is depended on strokeWidth and object scaleX, scaleY, so it will leave some space between object and controls/borders, see pic below :

```
     ctx.save(); // added

      if (!noTransform) {
        this.transform(ctx);
      }

      //this._setStrokeStyles(ctx);
      this._setFillStyles(ctx);
      if (this.group && this.group.type === 'path-group') {
        ctx.translate(-this.group.width/2, -this.group.height/2);
      }
      if (this.transformMatrix) {
        ctx.transform.apply(ctx, this.transformMatrix);
      }
      this._setOpacity(ctx);
      this._setShadow(ctx);
      this.clipTo && fabric.util.clipContext(this, ctx);

      this._render(ctx, noTransform);

      ctx.restore(); // added

      //@Tom

      this._setStrokeStyles(ctx);
      this._renderStroke(ctx);
```

![2015-05-28 8 58 32](https://cloud.githubusercontent.com/assets/4657101/7860506/52b176f4-057c-11e5-9122-6b8c37145b31.png)

**Comment by hellomaya** [comment]
@asturur 

Never mind, I fixed this part, by changing those calculation from strokeWidth * scaleX or strokeWidth * scaleY to strokeWidth, in object_origin.minix.js, and didn't find side effect yet.

**Comment by hellomaya** [comment]
Fixed it, in drawBorders:, change all strokeWidth / scaleX, and strokeWidth / scaleY to strokeWidth..

asturur Thanks for your great help.

**Comment by asturur** [comment]
i think the problem is just that people do not like scaling. they want to make bigger object.

i really think that scaling is fine as it is, maybe we should have some configuration options for controls to do something else than scaling.
consider that in a complex path group not scaling the stroke brings to unpredictable results.

also in svg graphic the stroke is affected by scale.

**Comment by hellomaya** [comment]
@asturur 

For SVG, this attribute could help to stop stroke being scaled, ```vector-effect="non-scaling-stroke" ```

**Comment by asturur** [comment]
vector effect is an attribute of svg 1.2
fabricjs support svg up to 1.1 as of now.
