### ISSUE TITLE
Shadow blur not being applied on scaled canvas

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#2244]
I have a scaled down canvas (720p scaled by approx 0.5) and when I apply a shadow to text, the blur will not appear to change until I scale the text slightly.

Both offset and colour will appear to change right away.

I am using 1.5.0, a scaling script and the guidelines script (from this repo)

Here is my code:

    var activeObject = canvas.getActiveObject();
    var shadow = activeObject.shadow;
    shadow.blur = blur; // value from input box
    canvas.renderAll();

Annoyingly, I cannot reproduce in JSFiddle :/

**Comment by asturur** [comment]
for canvas scaling you mean usd of viewport transform?

**Comment by paulcanning** [comment]
Is that a 1.5 feature?

I was using 1.4.0 up until this morning, and the scaling script was from this repo (a third part script I believe).

If there is a new way to scale the canvas, I'll take a look at that.

**Comment by paulcanning** [comment]
This bug is present in 1.5.0 (I assume you linked to the other issue as you might have thought this is a 1.4.0 issue, but it's not)

I mentioned 1.4.0 as i WAS using it, but not now and this bug is in 1.5.

Is there a new scaling feature in 1.5.0? How do I use it?

**Comment by paulcanning** [comment]
I have tried to replicate the issue in JSFiddle, but I am unable to. For whatever reason, it only affects my production application.

What I'd like to know, is there a new, proper way to scale a canvas? Can you point me in the right direction?

I am currently using an old script I used with 1.4.0 to scale my canvas, which may not be the best way now I am using 1.5.0.

**Comment by asturur** [comment]
I wanted just a text with some shadow setup. i would do the rest. I just did not want to set it up from scratch.

http://jsfiddle.net/hwtoc65g/2/

This is a text with shadow, correctly working, and there is some hint on how to use canvas zooming built in.
Other than zoom we have even panning ( search in the js file for panToPoint or something like that i do not remember ).

If there is no error on shadow, please close this issue.

**Comment by paulcanning** [comment]
Ah, I am not zooming out, I am scaling the actual canvas. My canvas is 1280x720, but I am then scaling it to be half the size, which scales down the canvas itself and all the assets.

Zooming out won't work, as the canvas would stay the same size :/

**Comment by asturur** [comment]
http://jsfiddle.net/hwtoc65g/3/

it' same.
I do not see any shadow related bug anyway. i close.
If bug popups i will reopen it.

**Comment by Strangebrewer** [comment]
I found this issue when I was having almost the same problem. If I scale down a canvas, any object that has a shadow with a blur loses the blur. Turns out, the problem (for me) was that `parseInt().toFixed(2)` returns a string, and while setZoom appears to otherwise work if you pass it a string for zoom (such as "0.74), it for whatever reason interferes with shadow blur.

In the JSFiddle mentioned above ([http://jsfiddle.net/hwtoc65g/2/)](http://jsfiddle.net/hwtoc65g/2/), if you change line 5 to `canvas.setZoom(parseFloat(canvasZoom).toFixed(2));` and then resize the canvas using the `zoom minus` or `zoom plus` buttons, you'll see the shadow no longer has a blur.

So if you're using parseInt to shorten the numbers for whatever reason, that will cause this problem. I'm using version 3.6.3.
