### ISSUE TITLE
Loading data from JSON; Can I set all images to have anonymous Cross-Origin?

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#2263]
I am loading images into canvas via loadFromJson(), but the images are served from Google Cloud Storage.

When trying to save the canvas to an image file, I encountered the Cross Origin issue, and my work around was to reload all images after loadFromJson finished, reloading them all with the anonymous Cross Origin option.

It works perfectly for most images, but I have come across a problem with SVGs.

When trying to load an SVG (hosted remotely) into my canvas using JSON, it won't even load the SVG, so I can't even reach the function for reloading images.

http://jsfiddle.net/yywsqvs5/ - fails, loading SVG from remote server.

http://jsfiddle.net/L0Lze0q5/1/ - works, loading a GIF from remote server

(both examples just load the image, i'm not doing the reload, as that is only for saving a thumbnail)

So, is it GCS to blame, or is there an issue with FabricJS?

If its GCS, I can submit an issue to them, but I wanted to check here first!

**Comment by asturur** [comment]
First jsfiddle is about a text and font family.
Second jsfiddle is about a svg that loads fine.

Are you sure you linked correct jsfiddles?

**Comment by paulcanning** [comment]
Fixed links.

**Comment by asturur** [comment]
You did not come across a problem with svg.
The problem is that the SVG has a filter on it, while the gif not.
Both of them do not have crossOrigin set on the json data.
To apply the filter chrome needs to access the canvas data and throw an error.
You can solve adding crossorigin:anonymous to your jsondata or removing filter.

I think that if you add the filter to the gif, you will get error.

fixed fiddle with crossOrigin:anonymous.
( does crossOrigin gets exported to object normally?)
http://jsfiddle.net/asturur/yywsqvs5/1/

**Comment by paulcanning** [comment]
Right, got ya.

I don't think cross origin gets exported when saving.canvas to json, but I'll check. Regardless, I can add it to my json object for loadFromJson (as it's served from a PHP script)

**Comment by paulcanning** [comment]
I added the crossOrigin property to the JSON object for any image asset and it seems to work OK.
