### ISSUE TITLE
Fix unit tests on http://fabricjs.com

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#2284]
http://fabricjs.com/test/unit/

**Comment by asturur** [comment]
did not we fix it before togheter with @sapics?

**Comment by kangax** [comment]
I thought so too but it's still failing for me — http://fabricjs.com/test/unit/

**Comment by sapics** [comment]
Thank you for mentioning me!

I guess that http://fabricjs.com/test/unit/ is different from kangax/master unit test.
Because the number of assertions is not same.
In my local PC which is build from kangax/master, [**2743 assertions** of 2743 passed, 0 failed] with #2286
In http://fabricjs.com/test/unit/, [**2580 assertions** of 2626 passed, 46 failed]
