### ISSUE TITLE
Dynamic pattern on scaled polygon deform the image

### ISSUE THREAD

**Issue by dumaron** [kangax/fabric.js#2304]
The tecnique shown in the [dynamic pattern demo](http://fabricjs.com/dynamic-patterns/) if used on a scaled polygon scale the background in a strange way.

You can see the bug in [this jsfiddle](https://jsfiddle.net/Lhesfabo/1/). I have applyed the background after scaling the polygon, but the image appears "pixellated".

Not only, the image is scaled by a ratio different from the one used to scale the polygon (2 in the example). This is somehow related to the instruction `img.scaleToWidth(p.getWidth())`: I have to scale the image by `p.getWidth()/p.getScaleX()` to fix this bug, but the image is still shown with poor resolution.

**Comment by asturur** [comment]
Scaling the image source patter is a choice.
Once the image is scaled on line 21 of the fiddle, it looses resolution because is scaled to polygon width that is smaller than original width of image. So its pixellated.

```p.getWidth()/p.getScaleX() = p.width```

Basically you are enlarging the polygon, to scale the image down to polygon width without loosing resolution.
Just do not scale image at allo to do not loose details.

https://jsfiddle.net/Lhesfabo/2/

**Comment by dumaron** [comment]
If you try the dynamic pattern demo you can see that the [used image](http://fabricjs.com/assets/pug.jpg) is big but, even if scaled to 100px, it doesn't become pixellated. I have updated the [jsfiddle](https://jsfiddle.net/Lhesfabo/4/) commenting only the polygon scale operation (line 15) and not the image scale operation (line 21), and the image still has got a good resolution.

Even if you try [your jsfiddle](http://jsfiddle.net/Lhesfabo/3/) uncommenting line 15, the image is pixellated.

I think the problem is still present. It's like the background image is scaled by the polygon's scale ratio, and this is why it's rendered with low resolution (from original width to 2x).

But this isn't right (at least in my opinion): this should happen if I first apply a background and then scale the polygon, and not if I apply the background when the polygon is already scaled.

Thanks for the hint of `p.width`. Since is the first time I use fabric I tought that `p.getWidth() == p.width`. Still sound strange to me, but after all it's just question of style and not a bug.

**Comment by asturur** [comment]
The problem is that a scaled polygon is a "zoomed" polygon.
So regardless of when you apply the the pattern, if the polygon as a scale factor of 2, the image will be scaled by 2 as well.
I think you have to try two different approaches:
1) enlarge the polygon point instead of scaling it ( modify points )
2) instead of a pattern, set fill to a custom function where you can reverse the scale factor.
