### ISSUE TITLE
Position text by its baseline?

### ISSUE THREAD

**Issue by Koosmann** [kangax/fabric.js#2320]
Is there a way to position text by it's baseline? 

This issue is somewhere between bug and feature request. The only options for originY relate to the bounding box (top, center, and bottom) and not the text itself.  It would be great have options that mirror the canvas' [textBaseline options](http://www.w3schools.com/tags/canvas_textbaseline.asp), so that you can position the text in a more precise way.
##

**Comment by marcodussin** [comment]
+1

**Comment by JamesTheHacker** [comment]
+1

**Comment by mkudej** [comment]
+1

**Comment by superruzafa** [comment]
+1

**Comment by Clonkex** [comment]
+1

**Comment by byends** [comment]
+1024

**Comment by asturur** [comment]
this feature has many +1. but what does it mean? text can be multiline and multi fontSize per line. what baseline should be taken in consideration?

**Comment by byends** [comment]
in my case, use it for backend (php) generate image. i want to make frontend is the same of backend.
so need textbaseline to define it's position.

**Comment by byends** [comment]
and textbaseline is the canvas feature, why do not to support it ?

**Comment by Clonkex** [comment]
@asturur Well I would think with multiline text you'd either give the option of choosing the line to position by, or always position by the first line. Pretty simple I think.

**Comment by asturur** [comment]
it does not make sense to me. at all.

Stretching, rotating, will need some fix.
Baseline are 5 kind of text positioning and something different from the `alphabetic` value is weird when you have different fontSize per line.

I have no idea wich is the equivalent of php for canvas, if any, but i think there would be many things to fix to make them similar. The effort is not worth.

If someone can come out with a PR to implement it i can still evaluate it.

**Comment by Clonkex** [comment]
It's just maths surely? Why does multiline make any difference at all? You can only position by one line at a time, so you just have to pick one (which would be the first line, or a user-specified line) and use that. What difference does it make if the other lines are different sizes? They don't affect the position. The positions of the other lines are relative to the line you're positioning the text as a whole by, even for rotations. I don't know about stretching because I don't know how that works; maybe it would be as simple as applying a multiplier to the positions for the other lines, maybe stretching would have to be incompatible with this form of positioning.

All it would do it give us another way to specify originY, nothing more. Maybe I will try to come up with a fix for this myself, but I don't know anything about Fabric's source so I don't know how well it will go.

**Comment by byends** [comment]
er, the featrue  is canvas official, is it ? I do not think its existence is meaningless.
why fabric.js define it with hard code value 'alphabetic'  ? but not  'top'  or others values ?
textBaseline is  base line，either Stretching or rotating can fix it !

**Comment by Clonkex** [comment]
Well @byends Fabric adds multiline text support among other things, which the canvas doesn't support by default, so it's fair that it doesn't have the same features as the standard canvas.

**Comment by asturur** [comment]
The point is that mantaining a widget for text editing with multi color, multi size, multi font text per line, is already hard as it is.

If the baseline would be bottom, how would you draw the world  game where `g` is font 80 and `ame` is font 20?  `alphabetic` is hardcoded and is gonna stay in that way for now.

For setting the position differently, is easier maybe, if someone wants to try it and open a PR i will review it.

**Comment by asturur** [comment]
re reading this i also had another thought.

Fabric position stuffs with originX and originY and that is not gonna change.
Text baseline is not a feature for fabric.
