### ISSUE TITLE
minScaleLimit get set to different value when width or height get set.

### ISSUE THREAD

**Issue by carlsa** [kangax/fabric.js#2329]
The minScaleLimit property does not seem to work on a circle in 1.5.0.

The properties work for rectangles and also works for circles in 1.4.0.

Example:
1.5.0 - http://jsfiddle.net/b82qjofg/
1.4.0 - http://jsfiddle.net/8jws8tbL/

Tested on Google Chrome for Windows 43.0.2357.130 and Firefox 39.0 for Windows.

**Comment by asturur** [comment]
The problem here is in this obscure line of code:

in object.class, _set function

```
      else if (key === 'width' || key === 'height') {
        this.minScaleLimit = toFixed(Math.min(0.1, 1/Math.max(this.width, this.height)), 2);
      }
```

As soon as width or height get setted, also does minScaleLimit.
but why?

**Comment by asturur** [comment]
maxScaleLimit does not exist just to say.

**Comment by asturur** [comment]
From the actual code ( i went back on the first version available on github ) it does not look like the feature minScaleLimit is user selectable.
Is just some internal limit to do not draw object too small, it gets adjusted using the inverse of width or height, wich is bigger, so that you will not go less than one pixel small.
@kangax any idea?

**Comment by carlsa** [comment]
Maybe it's a documentation bug (or maybe I misunderstand the documentation)? It looks like it is supposed to be accessible to the application here:
http://fabricjs.com/docs/fabric.Circle.html#minScaleLimit

Regarding the maxScaleLimit I indeed confused it with something else. I have removed the reference to it from the issue description.

**Comment by asturur** [comment]
I know, as of now i cannot do anything because i really do not know the feature under that code.
either a bug or a doc bug, waiting for @kangax to clarify.

**Comment by kangax** [comment]
Yes, I think it used to be a private property, just so that object wouldn't become 0 width/height when you're scaling it down with a mouse (it was some fun behavior when that happened). Then we exposed it and it's used as a constrain in `fabric.Object#set` (https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L11466) to constrain scaleX/Y of any object according to that property (including during the mouse/touch-based resizing).

I'm really not sure what that cryptic line is for :(

And I agree that we're strangely inconsistent about having `minScaleLimit` but not `maxScaleLimit`. I also wonder how popular this feature is in the first place... Perhaps no one is even using it :)

**Comment by asturur** [comment]
The point of that line is that
if minScaleLimit is a regulator to do not go "subAtomic" with objects ( i recently watched ant-man)
if Width or Height are very big, minScaleLimit can be even smaller of 0.1 ( why not 0.01 is a mistery )
i belive that we never found any bug because no one is using setters to set width and height and so no one is triggering that minScaleLimit auto setting.

either it goes private, either we remove that condition on the setter and let the user play with minScaleLimit

**Comment by carlsa** [comment]
The use-case for me was in conjunction with the gesture module where I used it to prevent users "pinching down" the scale an object to a size where is difficult to select it or to increase the scale with a pinch gesture again.

It is of course not very difficult to ensure by monitoring the scale in appropriate events instead, but the ```minScaleLimit``` property would have been a convenience.

**Comment by asturur** [comment]
After the recent transform bug i understood that the importance of minScaleLimit is just to keep the object at around 1 pixel minimum * not taking in account canvas.setZoom().
I'm not gonna touch it, it works fine as it is.

**Comment by d-kirsanov** [comment]
I think this code
```
     if (key === 'width' || key === 'height') {
        this.minScaleLimit = toFixed(Math.min(0.1, 1/Math.max(this.width, this.height)), 2);
      }
```
must be changed so it ensures that minScaleLimit is never less than this value, so nothing can be squeezed below 1 pixel, but if the user set it to a larger value already, it must respect that. For example:
```
     if (key === 'width' || key === 'height') {
        this.minScaleLimit = Math.max(this.minScaleLimit, toFixed(Math.min(0.1, 1/Math.max(this.width, this.height)), 2));
      }
```

**Comment by asturur** [comment]
i do not think is something meant to be used from devs.
If you want to do it, you can still override _set, execute your check for scale, then return early to skip the normal behaviour.

We do not get any feature changing what it does now, and we risk of introduce bugsm of wich we have plenty.

**Comment by d-kirsanov** [comment]
asturur: OK, but in that case perhaps it's better to remove minScaleLimit from http://fabricjs.com/docs/fabric.Object.html, or at least mark it as not intended for API users?
