### ISSUE TITLE
Stateful: false doesn't fire object:modified

### ISSUE THREAD

**Issue by sibbaldl** [kangax/fabric.js#2362]
(cross posting from google groups)

Hi guys, quick question for what I suspect is a perfectly understood situation:

I've created a fiddle https://jsfiddle.net/sibbaldl/f6q3agtf/1/  that demonstrates a simple situation whereby, if a canvas is initialised with "stateful:false" the "object:modified" event won't fire when moving the red square around and releasing the mouse button. The event will fire if stateful:true.
It took me a while to realise the cause of this in my code, because even with stateful set to false other events such as scale,rotate,move will fire.

Just wanted to know if this is expected behaviour.

Cheers!

Lee

**Comment by kangax** [comment]
Hm, I don't think this is expected or desired behavior, so marking as bug. Thanks for catching!

**Comment by asturur** [comment]
I checked stateful situation.
It looks like it has been left uncompleted.
stateproperties are lot, but the only check we have on "hasStateChanged" is on "finalizeCurrentTransform" 
We can fire object:modified anyway there, but at this point statefull will become useless because it will collect stateproperties before every transform, but it will never check them.
Also stateproperties include lot of properties ( fill, stroke, opacity... ) and those do not have correlation with transforms.

check #2890
