### ISSUE TITLE
ClipTo with SVG causes canvas to flash in draw mode

### ISSUE THREAD

**Issue by sibbaldl** [kangax/fabric.js#2381]
Hi guys

So I'm using an SVG shape as a clip path on the canvas, and it works well except that, when in free draw mode, there's a visible flashing effect when drawing on the canvas. Is there a way to avoid this? It happens on desktop and mobile

I've made a Fiddle https://jsfiddle.net/sibbaldl/4pb6hnvk/5/ that shows this behaviour.

Cheers :)

**Comment by sibbaldl** [comment]
Just wanted to add that this happens in 1.6RC1 as well as the current full release. 

Any help greatly appreciated.

**Comment by asturur** [comment]
The problem is that you are using the pathGroup.render function to clip a context of canvas.
This render function has various render and stroke.

In the main canvas you are drawing a white ellipse to clip your canvas.
Then red background is filling that white.

When mousedown start, the contextTop ( where drawing happens ) get clipped also with your white ellipse, but there is no red background there to fill up your white.

When mouse move starts, everything gets back to normal.

You should write your own clip function instead of using the pathgroup.render.

shape._render could be better maybe.

I do not have time to check deeper if that clip context on top canvas should be followed by a renderAll.

dirt hack: fill up your ellipse in svg with red instead of white.

**Comment by sibbaldl** [comment]
Hi, thanks for the advice. If I change the fill of the SVG eclipse to red that will remove the flashing, sure, but it doesn't avoid the underlying flicker issue that occurs still when you hold the mouse down (any existing paths drawn on the surface disappear until you release the mouse). Obviously that was a dirty hack as you say, so I guess it's to be expected.
I'll check out shape._render and see where that takes me

**Comment by asturur** [comment]
https://jsfiddle.net/4pb6hnvk/6/

in this fiddle a link to my modified version.
The lib execute a clearcontext after clipping on mousedown.

do not really know if there are side effects and no time to check.

**Comment by asturur** [comment]
modified function
```diff
    _onMouseDownInDrawingMode: function(e) {
      this._isCurrentlyDrawing = true;
      this.discardActiveObject(e).renderAll();
      if (this.clipTo) {
        fabric.util.clipContext(this, this.contextTop);
+        this.clearContext(this.contextTop);
      }
      var ivt = fabric.util.invertTransform(this.viewportTransform),
          pointer = fabric.util.transformPoint(this.getPointer(e, true), ivt);
      this.freeDrawingBrush.onMouseDown(pointer);
      this.fire('mouse:down', { e: e });

      var target = this.findTarget(e);
      if (typeof target !== 'undefined') {
        target.fire('mousedown', { e: e, target: target });
      }
    },
```

**Comment by sibbaldl** [comment]
woo, awesome! Changing the SVG to a red fill certainly appears to prevent any flicker, even of existing paths, with your modification above. 

I'll check it out - thanks a million :+1:

**Comment by sibbaldl** [comment]
I haven't spotted any issues during normal use of my app with this fix. Happy for issue to be closed but will leave open for your internal testing etc.

**Comment by asturur** [comment]
i think that when we clip with fabric objects, we have to set fill and stroke to '' in order to avoid renderStroke and renderFill to be executed.
