### ISSUE TITLE
Using canvas.toJSON() and then loadFromJSON

### ISSUE THREAD

**Issue by costa974** [kangax/fabric.js#2428]
This library is full of bugs! The last and blocking... using canvas.toJSON() and then loadFromJSON loses fillcolors and other properties... this lib should be versioned as 0.0.3 alpha

**Comment by asturur** [comment]
i think you got a 1.5.0 version bug.
please use latest version.

saving and restoring from json works good with the exception of some async issue or cors issues.

**Comment by costa974** [comment]
but I'm using v1.6.0-rc.1... eventually I will take a giant screenshot! To make a 300dpi print.

**Comment by costa974** [comment]
sorry for the outburst... but i'm tired

**Comment by kangax** [comment]
@costa974 Sure, we're full of bugs, known or unknown. Do you know a sufficiently complex software without any? We're constantly and relentlessly working on improving things, while having an extensive suit of unit and functional tests to avoid regressions. Do you know of many other canvas libraries that have one? `toJSON` and `loadFromJSON` are certainly one of the oldest and most robust parts of the library, so I highly doubt there's bugs with losing fill colors, considering that hundreds of apps use Fabric in production for exactly this kind of reason (saving and loading JSON). But in any case, a reproducible minimal test case is needed to quickly find a problem (if there's one) and fix it. Often times, people find that minimal test case actually works as expected and that the problem is somewhere on their application level.

**Comment by costa974** [comment]
OK sorry.. I will provide the proof... But I'm pushing the lib to the limit! mmmm... beyond its limit! :)

**Comment by armoucar** [comment]
I fell in the same issue. Objects that are inside groups don't get their `fill` attributes loaded.

http://codepen.io/armoucar/pen/JYGZKX

I'm experimenting the library and it is pretty awesome. Love the API and how easy it makes deal with canvas. Thank you! :)

**Comment by asturur** [comment]
Please @armoucar  use versione 1.6.0-rc1 and you should be ok.
This is old bug already fixed.

**Comment by armoucar** [comment]
@asturur Thanks you!
