### ISSUE TITLE
strokeWidth of 1 causing image mis-sizing

### ISSUE THREAD

**Issue by willtonkin** [kangax/fabric.js#2535]
We have been experiencing an issue where images will appear slightly blurry and and 1 pixel of width and height will be lost.

After performing a bisect I found the following commit to be the cause, as this problem was not occurring in v1.5.0:
80c3012646cd54c23cc2bb38306a6268574f815c
"Update object_origin.mixin.js"
    
After reviewing, it appears that the image object had a strokeWidth: 1, after explicitly changing this to 0 the issue is resolved.

Since I'd expect a 1:1 image with no scaling to be pixel perfect this looks like a bug.

My understanding of how strokeWidth is used is very limited but it occurs to me that either the default strokeWidth for an image should be 0 or we're using the wrong value when calculating object origins, I don't understand how strokeWidth is used so can't suggest a solution myself.

Here's a fiddle showing what I'm seeing: http://jsfiddle.net/willtonkin/hk8k1vwb/, using 1.6.0-rc.1 but it's still a problem at master.

**Comment by asturur** [comment]
yes, for images a strokewidth of 0 is really better.

you can redefine it for all library writing 
fabric.Image.prototype.strokeWidth = 0.

strokewidth is part of object dimensions.
it is default at 1 because in svg is same, and because in canvas is same.

when you have an image of 100 pixels, with strokewidth of 1, it is 101 pixels wide.

of you position it at x = 0 and y = 0, the image has 0.5px of border, then image start to drow. so every pixel of image is drawn crossing 2 pixels, and it becomes blurry.

**Comment by willtonkin** [comment]
Thanks Asturur for the insight.

As a new user of Fabric it was quite confusing to me, then again I was on the unstable branch :smile: 

Should I put together a pull request?

**Comment by asturur** [comment]
I do not know if this is something @kangax want to change ( the default image strokewidth ) 

There is not really stable or unstable branch. As of now we put maximum attention in every small pull request and we are mainly bug fixing than adding new features.
So the newer the better as i see it.

**Comment by willtonkin** [comment]
Awesome. Thanks for the help!

I'll close this for now then.
