### ISSUE TITLE
Group Opacity is set to subelements ignoring subelements opacity.

### ISSUE THREAD

**Issue by Ownelek** [kangax/fabric.js#2643]
When you set opacity for a Group object, opacity subelements is ignored.
Is it intender or just a bug? In my opinion subelements should have its own opacity, or at least, there should be a way to set its opacity for elements despite being in group.
JS Fiddle: https://jsfiddle.net/ymrucccn/4/

**Comment by asturur** [comment]
it should be multiplied. if not we broke it.

**Comment by asturur** [comment]
Opacity is in delegated properties, so if you give 1 to group opacity it descends to all objects.
and the inside rect becomes opacity 1 also.
It does not ignore it, it just overwrite it.

The problem is that if you give 0.5 to group you have 0.5 and 0.5 becomes 0.25.
And this is not acceptable in my opinion.

@kangax should we remove opacity from the delegates properties? Group opacity gets rendered over the objects anyway, i do not think we should delegate it.
