### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by arianitu** [kangax/fabric.js#2677]
Has anyone gotten fabric to work with webpack?

**Comment by asturur** [comment]
please for this kind of queation refer to google group or stack overflow. Here we manage bugs or nee features for fabricjs.

**Comment by playground** [comment]
@arianitu did you ever get fabric to work with webpack?

**Comment by itsazzad** [comment]
@playground did you ever get fabric to work with webpack or rollupjs?

**Comment by asturur** [comment]
if your system cannot install canvas for node, it won't work.

please put fabric library in a folder and instruct webpack that it is a dependency and not a part of the app

**Comment by playground** [comment]
@itsazzad, node-canvas is natively compiled.  In order for it to work with webpack we will need a statically compiled version.  I'm waiting for this [PR](https://github.com/Automattic/node-canvas/pull/813) to get merged.

**Comment by alanmimms** [comment]
I found that I could use Fabric in my project if I built on a system that could natively build node-canvas. Another sticky point I had was the `fabric` global variable, which was solved by [this useful stackoverflow question and accepted response](https://stackoverflow.com/questions/36984795/webpack-babel-es6-import-vs-require-for-fabric-js).

**Comment by asturur** [comment]
ok so i made this thing here:

https://travis-ci.org/fabricjs/fabricjs-webpack/

this is just an example, i took latest webpack, latest node ( to have latest npm ) and build a simple webpack bundle with fabricJS.

What i can see is that the build succedes, there are information stating that xmldom and jsdom are not bundled.

Then i test this on travis with a linux docker image where canvas can't be installed because libs are missing, npm throws warning says that an unmet optional dep is missing ( canvas ) but the intall does not fail. The build run.

So at least with latest tools chain everything works
