### ISSUE TITLE
Clipping no longer works once object is flipped.

### ISSUE THREAD

**Issue by smatthews1999** [kangax/fabric.js#2717]
I have been following the various clipping demos and find that as soon as I flip an object it will no longer clip correctly.  I am wondering if there is any fix for this.  It's a real killer for me.

Here is a jsfiddle demonstrating the issue.

http://jsfiddle.net/smatthews1999/ZxYCP/260/

**Comment by asturur** [comment]
The fix is writing a different clipping function.
You are clipping by fixed shape but you want draw this shape starting from object left and top. It's very complicated. Imagine of adding skewing here....

http://jsfiddle.net/asturur/ZxYCP/261/

this is a simplified version. no strange calculations, use internal fabric functions to calculate the inverse transform of the image and then clip by fix positions.

**Comment by asturur** [comment]
http://jsfiddle.net/asturur/ZxYCP/262/

cleaned a bit the clipTo: part. no reason to use _bind, pass name, just give reference to function.

**Comment by smatthews1999** [comment]
Very nice.  Thank you so much.  Your version should be in the docs most definitely!
