### ISSUE TITLE
Zoom and Pan events

### ISSUE THREAD

**Issue by Kampii** [kangax/fabric.js#2781]
How do I monitor these events? The inspector demo did not have that info.

**Comment by asturur** [comment]
there is not event for those actions. you get the the zoomToPoint, setZoom, and absolutePan ( if i remember good). If you want to use them with interaction you will bind them to some events. (mouse move, mouse click... )

**Comment by Kampii** [comment]
Thanks! The pan part could be tracked by some "key down" event together with "mouse move" event. However, how would I track the mouse scroll event which zooms in/out?

**Comment by StephanBijzitter** [comment]
@asturur Is there any reason why these property changes do not trigger events?

I can imagine there will be enormous performance issues when the event handlers are unnecessarily big,  but that should not be a concern for fabric as a library.

**Comment by asturur** [comment]
there is no particular reason.
We can add event for setZoom.
We can send the newZoom as parameter  considering that zoom can be fired in anyway, so there is no event to send. For panning we have 2 functions ( absolute and relative ) and they can fire event also... But what can they bring as parameter?
Do we send a reference to the canvas that is firing the event?

**Comment by asturur** [comment]
We have events mainly for things we do with mouse or keyboard ( object:added and removed are exceptions).
We do not have a standard way of triggering a zoom or a pan, that is why we do not generate any event.

**Comment by asturur** [comment]
Before adding this event i should be sure we do not use setZoom and other stuff internally for processing. i think we do in dataUrl but i can still change that.
Some event like onZoom and onPan would be nice but those would not fire when people change viewport transform manually.

**Comment by drinkspiller** [comment]
Hi, I see this was completed but cannot find code or documentation indicating implementation. Was this implemented or just "closed"? Thanks!

**Comment by asturur** [comment]
Zoom and Pan event haven't been implemented because are not event.
The user can't zoom or pan without code you have to write, so there is no way a user can zoom or pan without you as a developer knowing that is happening, so you do not need an event.

We add events only for code that is going to run because of user actions that you have no control over ( clicks, mouse move etc etc ).

Also 'object:added' on canvas is a mistake imho but it was there before i m not going to touch remove it.

Let me know if is clear why the event is not there and won't be there.
