### ISSUE TITLE
SVG Export for Textbox loses style on the 2nd line, and other issues

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#2829]
## Version
1.6.0

## Test Case
http://jsfiddle.net/jtweku/cdjth9k4/2/

there are 3 issues all with the second textbox, 
1. the second textbox lost the formatting after the first line when exporting to SVG.
2. space should not be there on the first beginning of the second line.
3. did you notice that the last character ('x') on the second line is not Bold, I use selectAll when applying style, unless Im not doing it right.  

## Expected Behavior
I have a fix for the svg export, remove the commented line of the code to see the correct behaviour 
_setSVGTextLineChars in the IText class should use the _getStyleDeclaration (because it is overridden in the Textbox class)

**Comment by asturur** [comment]
Case 1 has been solved by a recent PR. Case 2 has been reported already .

Case 3 we are going to check what is happening.

**Comment by jtweku** [comment]
@asturur, do you have the PR number ? 
I don't see the PR for fixing the _setSVGTextLineText to use the internal _styleMap in the textbox class. or it might be fix somewhere else ?

Thanks

**Comment by asturur** [comment]
#2780 and pr #2790

**Comment by jtweku** [comment]
Don't you still need to override the _setSVGTextLineText because the text is auto wrap and the _lines still have 1 length and not 2?  Otherwise it will use default the styles for the textbox.

https://jsfiddle.net/jtweku/cdjth9k4/1/

**Comment by asturur** [comment]
Ok i thought it was same issue. I will check also this one then.

**Comment by asturur** [comment]
case 2 solved

**Comment by asturur** [comment]
@jtweku check solution proposed in #2853, it should fix the issue.

About your proposed solution:
checking "this._styleMap[lineIndex]" with the iText class should produce an error ( did not test ) because iText does not have _styleMap.
Putting "this._styleMap && this._styleMap[lineIndex]" would not save us because iText does not have styleMap but can have styles[lineIndex].

It should be something like 

`this.styles[lineIndex] || (this._styleMap && this._styleMap[lineIndex])` that reads less nicely over this.hasStyleOnLine(lineIndex) in my opinion.

If you are experimenting with styled textboxes i would like you to test this solution because currently i do not have time.
