### ISSUE TITLE
npm Installation fails

### ISSUE THREAD

**Issue by stefanhuber** [kangax/fabric.js#2866]
Unfortunately, I cannot install fabric via npm. I have attachted my npm debug output.
My OS is Ubuntu 14.04.

I have globally installed node-gyp, as it was suggested here #2789. Are there any workarounds?

[npm-debug.log.zip](https://github.com/kangax/fabric.js/files/201375/npm-debug.log.zip)

**Comment by maximelebastard** [comment]
+1

**Comment by wovvan** [comment]
+

**Comment by wovvan** [comment]
try use bower install fabric, this helped me

**Comment by asturur** [comment]
I'll try to tag 1.6.0 and do npm publish asap.
Then with canvas 1.3.10 you can try again.

You may have problem with node 4+ anyway.

**Comment by wovvan** [comment]
hmm I don't know why it's isn't work.. I have node 4+ maybe problem with it. But i use bower, this work nice.

**Comment by stefanhuber** [comment]
Bower might be a solution, however as I manage all dependencies via npm I would prefer using it also for fabric. If it works with bower, I don't see any reason why it shouldn't work with npm...

**Comment by asturur** [comment]
I just made a PR #2872.
If travis system can npm current fabric, you should be able too.
Just need to npm publish it tagget as 1.6.0 final.

What do you think?

**Comment by asturur** [comment]
i run "npm install ."  in localhost after a git clone of the main repo tagget as 1.6.0 and the install went fine. Some warning about the use of execSync that has an old "gracefull" version, other than that it is working.

**Comment by stefanhuber** [comment]
Unfortunately, this doesn't works from me. I tried it on my machine, but still get the same errors...

If I search for fabric on npmjs I only get the rc.1 version. Could you run `npm publish` ?
https://www.npmjs.com/package/fabric

**Comment by asturur** [comment]
I do not have keys to publish, i'm waiting @kangax. What errors did you get doing
"npm install ." on a fresh cloned repository?

**Comment by stefanhuber** [comment]
oh sorry, maybe this was a misunderstanding! I want to use fabric inside one of my projects, so I install it as an NPM dependency. I do `npm install fabric`. This gives the errors, which I attachted above in the zip file.

**Comment by asturur** [comment]
This i know, and that is why last week i updated canvas to 1.3.12, jsdom to 3.1.2 and make sure that now you can use both node 4 , 5 and older versions.

This weekend i prepared the release for 1.6.0 which i cannot publish on npm by myself.
If you download the latest source code from github and in the folder where package.json is located, you run "npm install ." you should be able to install it. This installation, while it won't be usefull for your project, it will make you sure that as soon as 1.6.0 is published you are able to simply run  "npm install fabric".

Because you could get any other error, like the one that gets who did not install the necessary libs and build tools for node-canvas.
