### ISSUE TITLE
Conflict Issue of Fabric js with Prototype Js In Magento

### ISSUE THREAD

**Issue by mukeshcp** [kangax/fabric.js#2867]
Hi,

I am using fabric js version 1.5. While include fabric js into magento & creating canvas, its gives error on Code : CANVAS_INIT_ERROR = new Error('Could not initialize `canvas` element');

Also if we remove prototype js, then it works fine.

Please find screen-shot of Error code in fabric js.
![image_yv](https://cloud.githubusercontent.com/assets/12266888/14248986/300dbbbc-fa95-11e5-8d86-629b0dca284c.png)

**Comment by asturur** [comment]
Please provide a basic jsfiddle where this happens.

**Comment by mukeshcp** [comment]
Hi,
below is link :
https://jsfiddle.net/Mukesh_CP/342ojy63/

please help me to resolve this error.

if we remove prototype js, then it works perfactly.

Thanks,
Mukesh

**Comment by asturur** [comment]
To me it looks like canvas.fire is conflicting with prototypejs fire, i have to look it good, is not an easy check for me.

**Comment by asturur** [comment]
Anyway the problem is not happening here:
https://jsfiddle.net/342ojy63/56/

So please here you have prototype and canvas, please make the error happen in my fiddle.

**Comment by mukeshcp** [comment]
Thank a lot,
That was not issue of fabric js. But prototype js conflict with  jQuery.
Please let me know if you have suggetion.
https://jsfiddle.net/Mukesh_CP/342ojy63/

**Comment by mukeshcp** [comment]
Hi,
generated issue while add jQuery & add code of creating element using javascript : 
 var objWDiv = document.createElement("CANVAS"); 

https://jsfiddle.net/Mukesh_CP/342ojy63/79/

**Comment by asturur** [comment]
I do not have time to debug your application.
Anyway a simple console log made me understand that when you are creating canvas, you extended 
your options.canvas with something that added to it some prototypes.

Later making a lazy "for i in ...." you where passing to new fabric.Canvas a function instead of a string.

```for (var i in option.canvas) { }```

i made a check for type string, now you have another error for that is different and that you should be able to solve.

https://jsfiddle.net/342ojy63/80/

**Comment by asturur** [comment]
Please since there is no conflict at all between those 3 libs, for next question refere to stackoverflow.
