### ISSUE TITLE
draw polygon position error? why position not on mouse down point?

### ISSUE THREAD

**Issue by adu42** [kangax/fabric.js#2990]
look at: http://jsfiddle.net/ado42/Da7SP/91/

## Version
1.6.2

## Test Case
http://jsfiddle.net/ado42/Da7SP/91/

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

P.S.
"look at: fiddle link" is not enough to understand what is going on.
The problem is in yuor code, where you try to specify top and left for the plygon. You can't specify it while free drawing, let fabricjs set it.
