### ISSUE TITLE
Dynamic oCoords properties issue.

### ISSUE THREAD

**Issue by nksingh2** [kangax/fabric.js#3010]
Hi,

During moving,scaling and rotating the object i  see that the properties value of oCoords object like(tl,tr,bl,br) are not changing dynamically and only updated once we stop the event.

Is there any way to dynamically fetch the tl,tr,bl,br coordinates during scaling,rotating and moving.

Regards,
Nitin

## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
we don t do because calculation involved.

setcoords has been simplified a lot in the last 2 years and occords normalization has been made easier by the getTransformMatrix function. so if calculation are ok for your project you can easily do with canvas events scaling moving rotating. i ll try to push a snippet later.

**Comment by asturur** [comment]
I think you are interested in the main four corners:
Each corner is represented by:
Take untrasformed dimension of the objet:
dim = object._getNonTransformedDimensions();
each corner is represented by:
dim.x/2, dim.y/2 with all the four combination of signs:  + +, + -, - +, - -
Once you have all 4 corners do:
var matrix = object.calcTransformMatrix();
for each corner:  corner = fabric.util.transformPoint(corner, matrix);
And that is an updated corner.

We do not call setCoords() because this involves calculating 9 points and 36 corner points. Maybe just 4 points is acceptable and gives you an updated bounding box for the object

**Comment by nksingh2** [comment]
Thanks a lot,I will try and let you know.

**Comment by nksingh2** [comment]
Can you plz let me know the data type of corner.Is that a object with x,y or Array object.Please give
a sample example of corner about its syntax.

**Comment by nksingh2** [comment]
thanks i am able to solve my problem :)
