### ISSUE TITLE
Fabric.js News Ticker / Marquee

### ISSUE THREAD

**Issue by Powersurge** [kangax/fabric.js#3050]
I couldn't find any information about this in the Fabric.js docs or on this forum, and I even asked a question on [Stackoverflow](http://stackoverflow.com/questions/37734701/fabric-js-news-ticker-marquee), but I haven't received any responses back.  I would like to have a text object that can scroll like a news ticker when it gets placed on the canvas.  What I am looking for is an easy way to customize the look of a news ticker from an RSS feed and the Fabric.js library looks like the best fit for this. I would want it to work similar to adding a text object, but it would also have properties for scroll direction, speed, & loop.

Here's a sample jquery news ticker that is similar to what I am looking for with Fabric.js: http://www.jqueryscript.net/demo/jQuery-Plugin-For-Horizontal-Text-Scrolling-Simple-Marquee/

**Comment by ozooner** [comment]
Take a look at [fabric demos](http://fabricjs.com/demos/), there is plenty of information to get you started on animating, for an example the [cross demo](http://fabricjs.com/cross), but instead of changing object's width/height, you would manipulate objects position with left/top values. In my experience (this holds mostly true for browsers where html5 canvas hardware acceleration is not supported), CSS3 animations perform better if possible. You can also check this out: [html5-marquee](https://github.com/muchweb/html5-marquee)

**Comment by FeaRCODE** [comment]
This is more of a question, not a bug/issue. Stack Overflow is where you should ask this. You will need to animate "text" objects, etc. Look here for some details: http://fabricjs.com/fabric-intro-part-2, also please close this issue.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by Nosferatu31** [comment]
Since I got to this same issue, I'll leave a snippet here:
https://codesandbox.io/s/fabric-marquee-text-nmps73?file=/src/index.js
