### ISSUE TITLE
toDataURL on ipad large region

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3053]
## Version
1.6.2

## Test Case
http://jsfiddle.net/36yj97nk/21/

## Steps to reproduce
I make image editor. If i open ipad screenshot and try to crop some part of canvas, it cant load base64 when crop region is some big. On PC i dont have problem with it. 

Exist any workaraound of this problem? maybe some crop region dimension's limit ?

**Comment by asturur** [comment]
Please explain a little bit better.
What do you mean "i cant load base 64"? Can you see any error in console? does ipad have a console?

**Comment by Rad1calDreamer** [comment]
toDataURL({options}) return string, but if i open this url, that is clear page. Img doesnt have source and if i create new image by fabric.Image.fromURL() it will be transparent. It work only if exist fabric.Image  under crop region. I try replace image with rect and all work perfect, but i need image.

**Comment by butch2k** [comment]
Ok that's something i encountered as well when generating my viewport/navigator background image from main canvas. It worked perfectly on PC but not on iPad. Let me check how i solved it.

**Comment by butch2k** [comment]
Can't load your fiddle right now. But first try to desactivate retina support as it might scale the cropped image beyond the ipad's limits. i'll check your fiddle later today when i'm back home.

**Comment by Rad1calDreamer** [comment]
i make video.
1) i crop small part 
2) crop big part 

https://www.youtube.com/watch?v=aFrVdizD7bU

**Comment by butch2k** [comment]
Did you try the fix I suggested ?

**Comment by Rad1calDreamer** [comment]
> Limits of toDataURL() for iOS:

can i check that my crop is out of limit?

> canvas.enableRetinaScaling = false;

not help

**Comment by butch2k** [comment]
If retina is enabled: width*height*4 should  be under 5MP.
I'll double check in the apple dev portal if this limit still apply on latest devices/iOS version, as i'm quite certain it's a bit higher in the latest iOS versions.
What i can tell for sure is that very large pictures don't load in the canvas.

**Comment by butch2k** [comment]
@asturur I'm wondering if some of the hidpi issues we encounter with fabric and apple devices are not related to the way the backingstore is handled on those devices by Safari and the rest of the world....

http://www.html5rocks.com/en/tutorials/canvas/hidpi/

As far as i can tell on Safari the backing store of retina devices is already upscaled to take the hidpi ratio into account.

**Comment by Rad1calDreamer** [comment]
> width * height * 4 should be under 5MP.
thx! try catch this conditions, while dont find resolve

**Comment by asturur** [comment]
I searched this information so long with wrong googling.
I'm so happy to find out this backstoreratio because where it exsist i can stop having retina scaling influenced by browser zoom.
Other than that, do you think that safari make a retina enabled canvas by itself? i have to check this.
I will introduce a check for backstoreratio in the library for sure.

**Comment by butch2k** [comment]
IIRC apple recommends using webkitdrawimageHD to write data on retina devices. I'll check the Dev site when I'm out of the train. 



On Fri, Jun 17, 2016 at 9:35 AM +0200, "Andrea Bogazzi" <notifications@github.com> wrote:












I searched this information so long with wrong googling.

I'm so happy to find out this backstoreratio because where it exsist i can stop having retina scaling influenced by browser zoom.

Other than that, do you think that safari make a retina enabled canvas by itself? i have to check this.

I will introduce a check for backstoreratio in the library for sure.

**Comment by asturur** [comment]
is "context.backingStorePixelRatio ||
						context.webkitBackingtorePixelRatio ||
						context.mozBackingStorePixelRatio ||
						context.msBackingStorePixelRatio ||
						context.oBackingStorePixelRatio ||
						context.backingStorePixelRatio || 1;"
Something related to ipad iphones only?
I get just 1 on my macbook pro retina.

**Comment by butch2k** [comment]
Unfortunately i do not have any retina mac at hands :/ 
Did you test using Safari or Chrome ?
Is your screen configured as a retina display ?
