### ISSUE TITLE
Avoid floating point

### ISSUE THREAD

**Issue by DonovanCharpin** [kangax/fabric.js#3205]
Hi guys,

I was wondering if it would be possible to deal only with integers instead of floating points. I read some documentation which is saying that it can improve the canvas render. One article is on the [Mozilla website](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas)  and another [here](http://www.html5rocks.com/en/tutorials/canvas/performance/#toc-avoid-float) .

If it could improve the render, we could see something like that when the `Canvas` is created
```
new fabric.CanvasEx(canvasId, {
  avoidFloatingPoint : true
});
```

**Comment by neopheus** [comment]
I just checked all the drawImage function in the code

all variables for this function are integers

have you seen floating point variables?

**Comment by DonovanCharpin** [comment]
Thanks @neopheus It's already a good news that all the drawImage use integers, I didn't check.

Actually it's not when I draw but when I get coords from a polygon.

`polygon.getCenterPoint();`

So I have to be very careful on each action because all this data is stored in mongo and I have to store only integers. If I was able to trust the library to get only integer coords, it would be easier.

**Comment by asturur** [comment]
problem is not integer or float. when we draw on transformed canvas drawing
at 3,3 could end up to 6,6 if scale is 2, or any other number.

To draw pixel perfect and avoid blurriness, we should untrasform all
coordinates and work with non trasformed canvas. it would mean a new
library basically.

On Aug 25, 2016 19:48, "Donovan" <notifications@github.com> wrote:

Thanks @neopheus <https://github.com/neopheus> It's already a good news
that all the drawImage use integers, I didn't check.

Actually it's not when I draw but when I get coords from a polygon.

polygon.getCenterPoint();

So I have to be very careful on each action because all this data is stored
in mongo and I have to store only integers. If I was able to trust the
library to get only integer coords, it would be easier.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kangax/fabric.js/issues/3205#issuecomment-242479607>,
or mute the thread

**Comment by DonovanCharpin** [comment]
Oh ok @asturur , the best way is gonna be to store float coords in the mongo 👍
