### ISSUE TITLE
[Feature] - Subscript/Supscript

### ISSUE THREAD

**Issue by terrancesnyder** [kangax/fabric.js#3213]
All,

The company I work for deals heavily with graphic rendering and text layout of printed products and digital ones. The fabric library is fantastic, but we've run into a desire to scale and we'd like to open a bounty on fabricjs core to allow richer dynamic iText editing that support sub-script and sup-script.

We're open to many possible solutions but at the end of the day the solution needs to accomplish the following:

The ability to change a selection of character text to sub-script or sup-script. For example rendering 1.00 as 1<sup>00</sup>.
The solution needs to use the standard measureText(...) functions as we have overridden them to ensure kerning support via openType.js. Your solution need to be concerned with kerning support.
Here are some helpful links to get you started:

An example "poor guy/gals" superscript/subscript

https://forum.processing.org/two/discussion/6367/primitive-superscript-subscript-text-rendering
A simple video on what subscript and supscript means

https://www.youtube.com/watch?v=4boHA5wo5e0
Validation of work:

Modification of the http://fabricjs.com/test/misc/itext.html page with a button that shows "sub-script" and "sup-script" and the ability to select character ranges and subscript and sup-script them.

**Comment by asturur** [comment]
would like to write a bullet point list of feature instead of a video, with some images?

i kind of understood what we need to do, but i would like to know how it should parametrized.

i cannot assure this can go in the library, i think text needs a full rewrite and i m hesitant to write features now.

**Comment by denim2x** [comment]
I'd like to help out with this - say a plugin named 'super-text' or something like that

**Comment by asturur** [comment]
I m refactoring text completely so that it can do more simple things that combined will give also this functionality.
I will not modify the itext demo, since is just a show case of styles.
I would like understand who sub script and super script should be parametrized.
Text will get in style a dx, dy, angle property that will be used to displace characters and also support TSPANS from svg.
There will be an extra method ( in default build or as an extension ) to just use a set of this parameter to create a subScript/superScript ( a particular dY a particular fontSize in relation to the previous character probably or from the main fontSize)
All those things should be probably discussed, not for the bounty or this particular feature but just to make something that is the best for the general dev.
Fabric lies in a dangerous place between an editor sdk and a canvas lib, while i favor the canvas lib, many people seek for the editor sdk. And i have to balance the things so that we do not get a mix of disjointed methods.

**Comment by terrancesnyder** [comment]
+1 anything we can help with here @asturur ?

**Comment by poffringa** [comment]
@Eloverflow - Yes, this issue is still open.

**Comment by asturur** [comment]
i m working on it, i need time to fix text classes that are a big mess.
If they were not a big mess as they are, any dev could implement its own custom feature.

**Comment by denim2x** [comment]
working on a solution, reviewer: @asturur

**Comment by asturur** [comment]
@terrancesnyder  @denim2x is working on a solution with some costrains put by me, on which i m not that much flexible about.

Watching screens i see that you could have sup and sub on the same column, one under the other.
![image](https://user-images.githubusercontent.com/1194048/29352613-b18fe6b4-8267-11e7-8e21-e59d91c240cb.png)

This could be still achievable but before making denim work on it, i would like to know from you, since you are the ultimate approver for the bounty ( reason for which a dev is working on this solution ) if you could revamp the discussion being specific on the minimal product you are looking for.

**Comment by asturur** [comment]
I give you an introduction on what has been done so fare and is available on a branch:
There is a setSupscript and setSubscript that is configurable by 2 object with the same name that carry the information for font size reduction and displacement.

The values are chosen in a way that you will not get out of bounds if you apply them once.
If you apply them more and more, you will eventually go out of bounds, or if you manually enlarge the fontSize after it has been set at superscript.

Now denim2x i think is working on the cursor placement and eventually we need some adjustments for textbackground color or underline, this is unclear to me how it should work.

**Comment by terrancesnyder** [comment]
This is great. For the use case you provided above I dont think you need to worry about subscript and postscript on the same column of text. However, whichever is easiest.

Can you do an example of $1.00 with the "$" being subscript and the "00" being superscript?

**Comment by denim2x** [comment]
@terrancesnyder solution is [here](https://github.com/denim2x/fabric.js/releases/tag/v2.0.0-beta.6);
<img align="top" src="https://user-images.githubusercontent.com/8561801/29728349-32fb82ec-89e0-11e7-937c-97459e8ef42d.png">

**Comment by asturur** [comment]
i l make a demo on the fabricjs.com as soon as i can. unfortunately i m travelling now. also i ll.merge in the master branch as soon i can release 2.0

**Comment by Almax** [comment]
Hey guys!
Is this issue still active?

**Comment by asturur** [comment]
Is active, is resolved, is just not merged yet.

2017-11-30 17:21 GMT+01:00 Almas <notifications@github.com>:

**Comment by asturur** [comment]
The PR has been merged, i ll work on updating the demo pages to show it on the following days.
@terrancesnyder , @denim2x will claim the bounty, please check that the work is up to expectations.

**Comment by asturur** [comment]
@terrancesnyder  closing the issue. The feature is out, it has a dedicated demo, and toSVG support, and an example in the iText page as requested.

**Comment by terrancesnyder** [comment]
Awesome, lets give the bounty then after a quick review ;)

**Comment by asturur** [comment]
Sure be aware that the bounty is automatically given if you do not take actions in 15 days
