### ISSUE TITLE
Incompatibility in 1.6.4 with Text.fontFamily

### ISSUE THREAD

**Issue by awehring** [kangax/fabric.js#3261]
There is an incompatibility between version 1.6.3 and 1.6.4 with `Text` / `IText` `fontFamily`.

Up to version 1.6.3 the fontFamily could be defined like `"'Courier New', Courier, monospace"`.
With version 1.6.4 this definition is ignored (the displayed font defaults to `Times New Roman`).

The problem seems to be related with the ' (single quotes) within the " (double quote) string.
This issue might be introduced with #3191 - Fix: Quote font family when setting the context fontstyle.

## Version
1.6.4

## Test Case
```
var text = new fabric.Text('Hello world', {
 // Font works with 1.6.3 but not 1.6.4
 fontFamily: "'Courier New', Courier, monospace",  
 fontSize: 30,
 left: 100,
 top: 100,
 fill: 'red'
 });
 canvas.add(text);
```
http://jsfiddle.net/awehring/Da7SP/179/

## Steps to reproduce
Run the testcase, which is linked to fabric.js version 1.6.4. Gives wrong result.
Change fabric.js version to 1.6.3 (https://cdn.rawgit.com/kangax/fabric.js/1.6.3/dist/fabric.min.js). Gives correct result.

## Expected Behavior
In version 1.6.4 and 1.6.3: Shows "Hello World" in **Courier New** font.

## Actual Behavior
In version 1.6.4: Shows "Hello World" in **Times New Roman** font (wrong).
In version 1.6.3: Shows "Hello World" in **Courier New** font (correct).

**Comment by asturur** [comment]
well.
I guess users have to properly quote theyr fonts then.
I ll give it a looks.
Using the quotes was introduced to fix fontnames like 'Slabo 27px'

**Comment by mstock** [comment]
I guess I ran into the same problem, with `Arial, sans-serif` for the `fontFamily`. The way I understand [the CSS specification for `font-family` values](https://drafts.csswg.org/css-fonts-3/#family-name-value), something like `Slabo 27px` would not be a valid value in CSS, since `27px` is not a valid identifier, so the family name must be quoted. And I don't think that fabric.js must be more forgiving than CSS ;-). So in my opinion, expecting users to properly quote font-families would be fine. A link to the CSS spec or the [MDN page about `font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) in the documentation might be nice though.
