### ISSUE TITLE
Featur request : toBolb()

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#3283]
## Version
1.6.4

> Canvas toBlob() support added in Chrome 50

so...
plz add
```javascript 
fabric.Canvas.toBlob()
```

is good for some time need upload images with ajax

**Comment by asturur** [comment]
that would mean adding a backward compatible way for not so old browser that miss it ( safari ).
you can still calling it natively using fabric.canvas.lowerCanvasEl.toBlob()

**Comment by jimmywarting** [comment]
plz revisit/open

toBlob have been implemented in most browser now.
your utility function is better cuz it use quality=1 by default, you have a multiplier option too.

implementing it into fabricjs means we don't have to deal with IE,Edge prefixed msToBlob either. otherwise there is also method to convert [base64 to blob](https://stackoverflow.com/q/16245767/1008999) but i would prefer async versions of it (using toBlob + msToBlob)

maybe we could implement the [offscreenCanvas method](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/convertToBlob) instead of `toBlob`? just b/c it's promise based 👍

**Comment by jimmywarting** [comment]
my version

```js
fabric.Canvas.prototype.convertToBlob = function (options = {}) {
  const format = options.format || 'png',
        quality = options.quality || 1,
        multiplier = (options.multiplier || 1) * (options.enableRetinaScaling ? this.getRetinaScaling() : 1),
        canvasEl = this.toCanvasElement(multiplier, options)
  
  return new Promise((rs, rj) => {
    try {
      if (canvasEl.toBlob) {
        canvasEl.toBlob(rs, 'image/' + format, quality)
      } else {
        const b64 = fabric.util.toDataURL(canvasEl, format, quality)
        fetch(b64).then(r=>r.blob()).then(rs)
      }
    } catch (err) {
      rj(err) // maybe tainted
    }
  })
}
```

or less optimized: 

```js
fabric.Canvas.prototype.convertToBlob = function (options) {
  return new Promise((rs, rj) => {
    try {
      fetch(this.toDataURL(options)).then(r=>r.blob()).then(rs)
    } catch (err) {
      rj(err) // maybe tainted
    }
  })
}
```

**Comment by asturur** [comment]
i think since we have toCanvasElement, providing toBlob too seems like an extra?

Also if you do not have toBlob, why should you have `fetch` available?

I m not opposed to have toBlob in the canvas that acts as toCanvasElement, adding just the toBlob export. The code is already well divided to support that.

**Comment by jimmywarting** [comment]
just my version of it - currently i'm targeting more newer browser but may look into adding older support later

**Comment by asturur** [comment]
oh because safari still does not have it?

**Comment by jimmywarting** [comment]
safari has it.

**Comment by jsgoupil** [comment]
You provide `toDataUrl`, might as well provide `toBlob`. It's the most logical solution.
If the code is about the be modified, I'm not sure why we would go through the dataUrl first THEN to the blob?

I would see adding a `toBlob` on misc.js
And add to something similar to `canvas_dataurl_exporter.mixin.js`
(I don't know the your file structure).

Can someone change the title of this bug please... And re-open.
