### ISSUE TITLE
Maximum canvas width/height -Object doesn't dragging in fabric js

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#3293]
Hi to all,
     Here, we have working in fabric.js with creating design tool.We just set canvas width and canvas height more than "10000px" . for example, we assume that canvas width and height 8640px x10800px (96" inches x  120" inches) and we can drag/draw object in that canvas width and height.But its not working in that canvas.When object is dragging inside large canvas size , object is moving slowly and some time it was not move in canvas. 

![question 1](https://cloud.githubusercontent.com/assets/4013115/18870043/9171e1fa-84cc-11e6-8a18-85fd603cb214.png)

How to solve this problem?. Is there any limitation for canvas resolution ? How to rectify this problem ? Kindly review it and let me know your feedback.

THANKS
VIVEK KT.

**Comment by asturur** [comment]
8600 x 10800 is a big canvas.
I suggest you to work with the canvas sized as big as the screen needs and work with setZoom and Panning.

Please check fabricjs.com/kitchensink  and try to zoom with the wheel of the mouse, you will see that  you can zoom in as big as you need, and you can pan with the ALT and drag button if needed.

Having a big canvas is a problem because performances are slow.

**Comment by Vivek-KT** [comment]
thanks @asturur .I have reviewed that link .Any other solution for this? or we need to set big as the screen and using panning , we will work on it. Is there same resolution size will generated in as final output ? 

Thanks in advance. Kindly provide me any feedback.

THANKS
VIVEK KT.

**Comment by asturur** [comment]
for final ouput you do not have problem.
You just say canvas.toDataURL({ multiplier: X })  and it will X time bigger.
Take in consideration browsers limit that is at most 16k per size on firefox, chrome and 8k for internet explorer.

**Comment by bilalasif** [comment]
Hello,
I have an image with W: 2560 and H: 30000 When I set these values to the canvas dimensions 
This image appears:
![image](https://user-images.githubusercontent.com/1993983/103439408-72b47d00-4c5e-11eb-9ead-e27d752651e6.png)

What is the maximum limit that can be set on the canvas object that would not show above?

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/issues/3293#issuecomment-250184737

**Comment by shashank-brightness** [comment]
@asturur 
Is there any way we can get max canvas size for the browser which fabric is also using? I have case where i have applied filters for canvas directly but i am not getting filter applied image via `toDataUrl` and so what i am doing is taking this canvas and drawing on other virtual canvas.
Something like this

```

this.scaleFabricCanvas(factor)
drwingContext.drawImage(__canvas.getElement(), cropSelectionRect.left * factor , cropSelectionRect.top * factor, canvasCropWidth * factor, canvasCropHeight * factor, 
                    (this.finalImageWidth - drawWidth) / 2, (this.finalImageHeight - drawHeight) / 2,  drawWidth, drawHeight);
```

```
scaleFabricCanvas(factor) {
        __canvas.setViewportTransform([factor, 0, 0, factor, 0, 0])
        __canvas.setDimensions({
            width: __canvas.getWidth() * factor,
            height: __canvas.getHeight() * factor
        })
    },
```

I already have image size limitation around 8k but when smaller cropped area needs to be projected to bigger size canvas, factor becomes very huge and it can not scale beyond that point because factor is division of cropped size and final image size. Let's say croppedSize is 10x10 and image is 2000*2000 

If i draw canvas directly without scaling (i.e. scaleFabricCanvas) then i am getting blurred output.  I anyhow need filter on whole canvas level and get exact output via `toDataUrl` with filters applied on result.
