### ISSUE TITLE
[BUG] iText/Textbox empty character styles are ignored (not resetting to default)

### ISSUE THREAD

**Issue by temuri416** [kangax/fabric.js#3337]
## Version

1.6.5
## Test Case

http://codepen.io/tmrczk/pen/gwZENY
## Steps to reproduce

Open [http://codepen.io/tmrczk/pen/gwZENY](url) in Chrome/Firefox.
## Expected Behavior

"FOO" part should **not** be underlined, should **not** have background color, should **not** be italic.
## Actual Behavior

"FOO" part is underlined, has background color and is italic. However, it is correctly red and has size 160.

``` js
text.setSelectionStyles({
  fill: 'red',
  fontSize:160,
  fontStyle: '',
  textUnderline: '',
  textBackgroundColor: ''
})
```

It is not possible to reset text formatting properties to their empty defaults. This is the relevant part:

https://github.com/kangax/fabric.js/blob/master/src/shapes/itext.class.js#L772

Thanks!

**Comment by asturur** [comment]
so the bug is for sure for the backgroundColor, while not for the other properties.
you can set fontStyle: 'normal' and textDecoration: 'none' to make them render correctly.
The backgroundColor needs a fix.
Same kind of fix of textDecoration, skip rendering if the style has some property regarding the underline and then render char by char.

**Comment by asturur** [comment]
#3680
