### ISSUE TITLE
OS X special character keyboard does not work with IText

### ISSUE THREAD

**Issue by StephanBijzitter** [kangax/fabric.js#3343]
## Version

1.6.2
## Test Case

http://jsfiddle.net/k31660m4/1/
## Steps to reproduce

Click on the text area to focus, and type the `õ` character. On OS X, you can do this by pressing the `o` key, holding it down, and then selecting the correct character from the menu that appears.
## Expected Behavior

The text changes into `Hellõõ`.
## Actual Behavior

The text changes into `Hellõo`.
## Additional information

I have tested this on the following devices:
- Desktop, Windows 7, Opera: works as expected.
- Desktop, Windows 10, Chrome: works as expected.
- Laptop, OS X, Opera: does _not_ work as expected.
- Laptop, OS X, Chrome: does _not_ work as expected.
- Tablet, Android, Chrome: works as expected.
- Tablet, iOS, Safari: works as expected.

Copy/pasting the `õ` character into the textfield does work correctly. This rules out rendering issues, which would mean this issue is probably a problem with input itself.

**Comment by neopheus** [comment]
no problem on Chrome 54 / Mac OS Sierra

**Comment by StephanBijzitter** [comment]
Strange, with Chrome 54 and Sierra I can still reproduce this bug. I'll record a video tomorrow at the office and edit it into this comment.

**Comment by asturur** [comment]
I fixed this, at least in chrome.
There are problems that do not let me help fixing in firefox.
That popup is hard to handle i have to say, because it does not fire a specific event for when you press.
Example if you press 3 to choose something, you just get a 3 keypress and that is confusing, at least. The oninput get fired but with no knowledge of what is going to change, if the character should be added or replaced.

**Comment by asturur** [comment]
this is fixed in latest master finally fabric 2.0.0-beta0
