### ISSUE TITLE
zoomToPoint - wrong coordinates after panning  / zooming 

### ISSUE THREAD

**Issue by boten** [kangax/fabric.js#3371]
# Steps to reproduce
1. Use the mousewheel to zoom in and out and then press the "go to blue dot" button 

## Expected Behavior
pressing the button should always bring the blue dot to the center of the screen and the zoom level to : 2 , no matter what previous image state was before (zoomed or panned to other location) 

## Actual Behavior
the image moves to random locations ? it seems that panning the image / zooming it,
 mess up the entire move to function.

http://codepen.io/anon/pen/jrdjJm

**Comment by asturur** [comment]
The expected behaviour is wrong. Zoom to point does not center the viewport around a point, but zoom the viewport in a way that the selected point is steady.
Also the fiddle is full of custom code and while you are using the standard fabricjs zoomto point function, you are using a custom zoom function.

Please use mousewheel to zoom in a point of the canvas in fabricjs.com/kitchensink to see what to expect from zoom to point.
