### ISSUE TITLE
Changing image src changes image dimensions after updating canvas.js from 1.6.4 to 1.6.6

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3385]
## Version

1.6.6
## Test Case

https://jsfiddle.net/knrr8do8/1/ - How it works now
https://jsfiddle.net/2n4vmum7/ - How it should work and worked before
## Expected Behavior

Image src replaces with same image dimensions
## Actual Behavior

After updating image src object resizes to new image size

Found that this part of code works well:

```
obj = canvas.item(1).getElement();
obj.setAttribute("src", url); 
```

But how can i get item index of selected object to use this way?

**Comment by asturur** [comment]
why you post two fiddle with same fabric version and different code.
And you label them before and after?
Please refine the fiddles to show what you mean.

**Comment by ncou** [comment]
Hi,

Your ticket is not really clear, I suppose you want to change the source of the image and get the right width/height.

You should use the setSrc() function with a callback to refresh the canvas, instead of using setAttribute('src').

Here is a working fiddle. Close the ticket if it's working for you.
https://jsfiddle.net/2n4vmum7/1/

PS : i don't think your 2nd example ever worked fine with other fabric version.

**Comment by DangerD256** [comment]
That's not working for me, it resizes image dimensions on canvas, dimensions must be the same even image is stretched... How can i make it?

**Comment by ncou** [comment]
Ok, if i understand : you want to change the src of the image but keep the initial width and height ? even if the result is stretched ?

If it's that, you need to store the original values, and apply them once you have changed the src value.

I see no bug here, and i don't understand why you don't use the code of the 2nd fiddle if it's the variant you seek.

I am a bit lost, but try this fiddle, it's like your first fiddle but with the strech based on the orignal w/h of the picture.
https://jsfiddle.net/knrr8do8/2/

**Comment by DangerD256** [comment]
https://jsfiddle.net/2n4vmum7/2/

This bug caused due to zoom out functionality...
Check fiddle...

**Comment by ncou** [comment]
Ok, i am still totaly lost, in your fiddle you don't change the src ? it was your need when you have created the ticket, are we drifting from the orignal topic ?

i see a strange behaviours if i click on the button, the setHeight is false because you are using a custom "zoom()" function. If i try the builtin function canvas.setZoom(), it's working fine.

https://jsfiddle.net/2n4vmum7/3/

**Comment by DangerD256** [comment]
i've found solution, kinda stupid but works:
```
var height = activeObject.getHeight();
activeObject.setHeight(activeObject.getHeight());
var multiplier = height/activeObject.getHeight(); 
.. changing image src...
activeObject.setHeight(height*multiplier);
```
i don't know if that is bug or not, but it fixed for me now.

**Comment by DangerD256** [comment]
> i see a strange behaviours if i click on the button, the setHeight is false because you are using a custom "zoom()" function. If i try the builtin function canvas.setZoom(), it's working fine.
Built in function doesn't resize canvas, it only resizes content in canvas, and i need to zoom in/out whole document as in image editors such as photoshop

**Comment by ncou** [comment]
When you get the height value, it's after the scaleY factor is applyed, but when you set the height, you need to set the original value because the scale factor will be applyed after.

So you can : store the scale factor, reset the scale factor to 1, change the scale factor with the saved value.

Or you can reverse the scale factor when you apply the value : 

var scale = canvas.getActiveObject().getObjectScaling();
var H = canvas.getActiveObject().getHeight() / scale.scaleY;    
canvas.getActiveObject().set({height:H});

In fact it's what you are doing in your twisted solution above, by deducing the reverse scale factor.

**Comment by asturur** [comment]
To get help on an issue tracker that is not meant for help, the only way is express in a fast and effective way your problem. I cannot really understand what is the problem/bug or desired behaviour because i m not able to extract it from the custom code.

If the point of this topic is getting ANY IMAGE to take same dimension and place of an another image, the easiest ways is:

1) create a new fabric object.
2) collect top, left, getWidth and getHeight of the old image.
3) set top and left of the new image to the old.
4) set scaleX of the new image to  getWidth() of the old divided the width of the new one, same fore height with scaleY
5) place new image on canvas.

Also please investigate how to use fabricjs internal zoom more than a custom one that is changing objects properties.
