### ISSUE TITLE
Fabric Clone in Group not draw Controls when select new Cloned Object

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#3411]
## Version
1.6.6

## Test Case
http://jsfiddle.net/samael205/nkppvada/

## Steps to reproduce
Select the two objects, Do Ctrl+c & Ctrl+V and select any of the new objects 

## Expected Behavior
In the new objects, the scaling controls should appear

## Actual Behavior

The scaling controls not appear until you select all the objects with the mouse. In some cases the object can not be selected.

**Comment by ncou** [comment]
Hi,

I think there is a problem in the properties array you are passing to the clone function.
Your paste function is also cloning again the cloned objets in the clipboard.

Here is a working fiddle : http://jsfiddle.net/nkppvada/1/

By the way you should check the topic :https://github.com/kangax/fabric.js/issues/2974
With the fiddle because now the clone function work with a callback for sync and async objets so the "Klass" check is not needed.

Hope this help.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

Also this issue contains custom code for copy pasting, is not something we can help with
