### ISSUE TITLE
Unable to maintain thickness of strokeWidth while resizing in case of Groups in Fabricjs

### ISSUE THREAD

**Issue by shaktippatel** [kangax/fabric.js#3431]
## Version
1.6.6

## Test Case
http://jsfiddle.net/Subhasish2015/y344vs5s/1/

## Steps to reproduce
1)Open above fiddle link
2)resize the circle , check the size of border (thickness of border remains the same on re-sizing)
3)Now resize the rectangle and text(group) , expected result is thickness of border must be same throughout but that doesn't happens.

## Expected Behavior
Maintain thickness of strokeWidth while resizing in case of Groups

## Actual Behavior
Unable to maintain thickness of strokeWidth while resizing in case of Groups in Fabricjs

**Comment by asturur** [comment]
There is a basic misunderstanding of 'expect behaviour'.
Fabric do not resize on scaling, if you write custom code to do it, is not part of this issue tracker to make it work.
Said so:
your switch case in the code does not have a case for 'group'.
while group is scaling, the inner object are not receiving the scale event.

You could manually apply the same function to the child objects, calling: `group.forEachObject(function(object){})`
but you would probably have problem with position inside the group. you cannot change width and height of objects inside group without recalculating theyr position and group size.

i suggest you to modify just the stroke tickness on scaling, for object or inner objects instead of trying to change width and height.

i m sure on stackoverflow there is some similar question already answered.
