### ISSUE TITLE
Control borders with scaled objects

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3455]
Hi,

Tested with the v1.7.0 release.
I found something strange when the objects have a scale value.

If i scale up, an image and a rect object, if i made a selection with both objects, the blue control have more space than the image object.
It seems to me there is by default 1px beetween the blue frame and the object, but in the case of "rect object" the space beetween the object and the frame seems to be also scaledUp.

Not really sure to explain correctly myself, here is a screenshot (i put in red the diff), you can see the gap beetween the blue frame and the rect object, but not in the case of the image object.

![image](https://cloud.githubusercontent.com/assets/16743322/20498362/37211ba8-b02d-11e6-909c-482a9c1aada7.png)

Here is the fiddle. Select both object to reproduce.
http://jsfiddle.net/yvo89upg/3/

Is this normal or possibly a bug ?

Thank you for your help.

**Comment by asturur** [comment]
That should be normal.
By svg defaults objects have 1px border transparent.
We respect this svg default, useless on canvas, because we want to import them easily.
The borders scale with object.
If you give a color to the stroke of the rect or if you set strokeWidth to 0 that will remove the transparent scaling space between object and controls.
We disabled standard border for images because that was really hurting crispness and i hope we restore it manually during svg import ( did not check that ).
