### ISSUE TITLE
Update to 1.7.0 fails.

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3463]
![image](https://cloud.githubusercontent.com/assets/17032489/20727480/588462fe-b682-11e6-8500-589f011291d4.png)
Any ideas?
Or i can try to create fiddle with saves json.

**Comment by lukasvan3l** [comment]
I have the same problem

for googleability sake I'll paste the error (@DangerD256 please do so as well next time, then I would have found this post a lot sooner!)

```
fabric.js?3634:25776 Uncaught TypeError: Cannot read property 'save' of undefined(…)
  _splitTextIntoLines @ fabric.js?3634:25776
  _initDimensions @ fabric.js?3634:25550
  initialize @ fabric.js?3634:21525
  (anonymous function) @ fabric.js?3634:1743
  callSuper @ fabric.js?3634:1772
  initialize @ fabric.js?3634:22544
  (anonymous function) @ fabric.js?3634:1743
  callSuper @ fabric.js?3634:1772
  initialize @ fabric.js?3634:25521
  (anonymous function) @ fabric.js?3634:1743
  klass @ fabric.js?3634:1791
  addText @ mycode.js?c49a:241
```

It only breaks if I `addText`, not if I add an image.
The problem is that `ctx` isn't set.

I reverted back to 1.6, works fine there :)

**Comment by asturur** [comment]
this has been solved in current master. did not have time to re release 1.7.1 as official fix.

**Comment by asturur** [comment]
try to release today, tonight.

**Comment by lukasvan3l** [comment]
awesome, thanks for the quick fix!
