### ISSUE TITLE
After 1.7.0, groups clip content that draws outside their bounds. Prior to 1.7.0 they did not.

### ISSUE THREAD

**Issue by dennisrjohn** [kangax/fabric.js#3485]
## Version
1.7.0

## Test Case
We are using a group with a rect that draws outside it's bounds to draw borders around an image. Prior to 1.7.0, this worked fine, but now the group clips everything outside it's bounds.

In the jsfiddles below, click the Draw with border button, the 1.6.7 example shows the border, the 1.7.1 example does not.

jsfiddle with 1.6.7:
https://jsfiddle.net/anq8ho81/

jsfiddle with 1.7.1:
https://jsfiddle.net/0nk6sbsv/

## Steps to reproduce
1. Add a group.
2. Create a Rect that extends beyond the bounds of the group.

## Expected Behavior
The rect displays beyond the bounds of the containing group.

## Actual Behavior
The group clips the rect to its bounds.

*If this is the new intended behavior, can a property be added to override this back to the old behavior? Or to override the group's clipRect with a larger one?

**Comment by asturur** [comment]
I do not see any difference in the fiddles.
Anyway two things:
1) fabric 1.7.0 has object caching that you can disable if you need to draw out of controls.
read this: http://fabricjs.com/fabric-object-caching

2) fiddle must be small, simple, without to many button to press and read unless the bug is interaction with mouse. You have to remove your custom logic from the fiddle and reduce to the minimal amount of code to make the thing fail.

In this way is easier for me to review and to fix.

**Comment by dennisrjohn** [comment]
Sorry about that. 

Here is an updated Fabric 1.6.7 jsfiddle:
https://jsfiddle.net/anq8ho81/2/
And 1.7.1 jsfiddle:
https://jsfiddle.net/0nk6sbsv/2/

**Comment by dennisrjohn** [comment]
Also, I'll try disabling object caching.

**Comment by dennisrjohn** [comment]
Turning off object caching fixed the issue.

**Comment by asturur** [comment]
ok now i see the issue.
Unfortunately i do not want to consider this a bug.
Object are meant to be inside the controls ( well normally controls are built outside the controls.
If you need to use the library with controls objects outside controls, you will have to disable object caching.
For images is not active on default, for simple geometric shapes is not even so usefull as you may have read in the small guide.

**Comment by dennisrjohn** [comment]
Makes sense.

Thanks.
