### ISSUE TITLE
[BUG] Vertical & horizontal lines in a group are exactly half the length they should be

### ISSUE THREAD

**Issue by temuri416** [kangax/fabric.js#3517]
## Version
1.7.1

## Test Case
http://codepen.io/tmrczk/pen/XNBaMy

## Steps to reproduce
Use any browser.

## Expected Behavior
Red vertical and horizontal lines should stretch the entire gray area (which is the canvas background color).

## Actual Behavior
Red vertical and horizontal lines are exactly half of the length - **450**px instead of **900**px and **581**px instead of **1162**px.

The blue line that's outside of the group has correct height.

Version 1.6.5 used to render the red grid correctly.

![image](https://cloud.githubusercontent.com/assets/3987203/21067641/a1026d40-be3a-11e6-9815-c66948ceaeb1.png)

```js
var gridWidth = 900;
var gridHeight = 1162;

var canvas  = new fabric.Canvas('c', {
  backgroundColor: "#cccccc",
  width: gridWidth,
  height: gridHeight
});

var gridSizePX = 100;
var pageGrid = new fabric.Group([], {left: 0, top: 0, width: gridWidth, height: gridHeight, originX: 'center', originY: 'center', evented: false, selectable: false});

var lineOption = {stroke: 'rgb(255,0,0)', strokeWidth: 1, selectable: false, evented: false, strokeDashArray: null};
// first loop for vertical line
for (var i = Math.ceil(gridWidth / gridSizePX); i--;) {
  pageGrid.add(new fabric.Line([gridSizePX * i, 0, gridSizePX * i, gridHeight], lineOption));
}
for (var i = Math.ceil(gridHeight / gridSizePX); i--;) {
  pageGrid.add(new fabric.Line([0, gridSizePX * i, gridWidth, gridSizePX * i], lineOption));
}
canvas.add(pageGrid);


var lineOption2 = {stroke: 'rgb(0,0,255)', strokeWidth: 3, selectable: false, evented: false, strokeDashArray: null};
var line = new fabric.Line([720, 0, 720, gridHeight], lineOption2);
canvas.add(line);
```

Thanks!

**Comment by asturur** [comment]
i see a group with origin in center positioned at 0,0. i expect just a quarter of group to be visible instead of all group. make it origin top,left or change group position is my guess

**Comment by temuri416** [comment]
I tried to play with origin & coordinates, but nothing helps.

Clearly, this is a regression issue. Everything was fine in 1.6.6 version.

**Comment by ncou** [comment]
Disable the object caching an the lines cover all the area.
http://codepen.io/anon/pen/LbBJvp

**Comment by asturur** [comment]
Object caching is not something to disable to fix out of bound glitches. if the group needs to cover all the area width and height should be as big as needed. the  object caching can be used normally.

**Comment by temuri416** [comment]
@asturur I do not quite understand your position - is there a bug or do you think I should further play with the code?

**Comment by asturur** [comment]
i guess there is bug in the way group is done. i did not have chance to sit
down and try it yet

**Comment by asturur** [comment]
So the problem is this:

The group needs to calculate left, top, width and height with the object inside.

problem 1:

The group is in top left 0,0 with originX/Y in the center. So it is effectively as big as needed but is centered over the 0,0 of the canvas , and 3/4 of the area is outside it.
(i scaled down the the group and made it selectable to better explain it)
![image](https://cloud.githubusercontent.com/assets/1194048/21079512/00590e02-bf94-11e6-8089-ffa0b72d8057.png)

problem 2:

the group needs to update coordinates based on what is inside.
if in the last line added you use `.addWithUpdate` instead of just `.add` everything works.
Old width and height get overridden with the new one and top left get changed with the right one needed to have all the lines in place.

The code itself is a bit bad organized. It would work better to create first lines and then the group:

```javascript
var lineOption = {stroke: 'rgb(255,0,0)', strokeWidth: 1, selectable: false, evented: false, strokeDashArray: null};
lines = [];
// first loop for vertical line
for (var i = Math.ceil(gridWidth / gridSizePX); i--;) {
  lines.push(new fabric.Line([gridSizePX * i, 0, gridSizePX * i, gridHeight], lineOption));
}
for (var i = Math.ceil(gridHeight / gridSizePX); i--;) {
   lines.push(new fabric.Line([0, gridSizePX * i, gridWidth, gridSizePX * i], lineOption));
}
var pageGrid = new fabric.Group(lines, {originX: 'center', originY: 'center', evented: false, selectable: false});
canvas.add(pageGrid);
```
