### ISSUE TITLE
Stretching textbox after group move

### ISSUE THREAD

**Issue by howdu** [kangax/fabric.js#3608]
## Version
1.7.2

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce
1. Select group of textbox
3. Move position of group
4. Deselect group

Comparing the object data before/after shows that only the width changes, scale/height remain the same. 

![fabricjs com-kitchensink](https://cloud.githubusercontent.com/assets/533658/21645382/ae252752-d289-11e6-948f-52580db8dc28.png)

![fabricjs com-kitchensink 1](https://cloud.githubusercontent.com/assets/533658/21645384/b01879c4-d289-11e6-918d-1cf1a21a2a49.png)

![fabricjs com-kitchensink 2](https://cloud.githubusercontent.com/assets/533658/21645391/b2a80baa-d289-11e6-8350-e98c636711e5.png)

**Comment by asturur** [comment]
oh wow. this sucks.
Need to delay 1.7.3 and fix it :(

**Comment by asturur** [comment]
Ok is not a fabricjs `bug` is a kitchensink problem since the textbox is started with a 0.5 scale and this makes mess to the textbox logic.

I agree that this is not right to the root, but text support will be rewritten and i do not think we should address this now.
I think textbox should be scalable as any other object.

**Comment by howdu** [comment]
Wondering if you found a fix for this? I'm still getting it on a project but not on the kitchen demo anymore.  

After moving a group of text the scaleX is reset to 1 but scaleY remains correct.

**Comment by asturur** [comment]
the textbox has the same bug. i do not think i fixed it.
The whole textbox scaling approach is wrong.
