### ISSUE TITLE
Group rotation originX and originY is always set to left top if rotated programmatically!

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3616]
## Version
1.7.3

## Test Case
https://jsfiddle.net/human_a/2ton6aqg/

## Steps to reproduce
Select multiple objects and try rotating the group **using the range slider input below the canvas**.

## Expected Behavior
Just like single objects rotate with originX and originY set to center if they are set like so, at creation point. 

## Actual Behavior
But there is no way to set it when multiple objects are selected and it defaults back to top left.

## FYI
This is not the case if I try to rotate the group using the rotation handle on the selection bounding box. How can I have the same behavior for my manual rotation too?

**Comment by ncou** [comment]
Hi,

It's working with setAngle(), because it force the "originToCenter" while the setter doesn't do it or made a reset (i don't remember).
I think this function setAngle() will disapear in v2.0 for a "rotate" function, but I don't know if the angle setter will still be here and respect the origin or not.

Here is the working fiddle.
https://jsfiddle.net/2ton6aqg/4/

**Comment by asturur** [comment]
Is controversial. But if we set an angle it rotate on topleft, strangely because the canvas is on the object center, something i do not get ( yet ).
setAngle will become rotate() or setRotation(), i would remove all composed setter ( setThis, setThat ) since we have set() that does lot of stuff.

Strange also that we are using set in both cases here.
Need to give a look, i do not think there is a bug but better get the exact reasons behind this

**Comment by human-a** [comment]
@ncou Good point, thank you very much!

@asturur Thanks for the additional info, certainly useful tips.
I hope there would be a decent migration guide once the version 2 is out to make a smooth transition for all.

**Comment by ncou** [comment]
for the migration doc, you can find the incompatibility list/broken features in the Wiki : 

https://github.com/kangax/fabric.js/wiki/Fabric-2.0-Changes

**Comment by asturur** [comment]
ok i figured out what is going on.
Simply the activegroup is not originX or originY set to center.
That's all.

You can either you activeGroup.setAngle()
https://jsfiddle.net/2ton6aqg/5/

or you can make the group center aligned
https://jsfiddle.net/2ton6aqg/6/
