### ISSUE TITLE
calcLinePoints() method is giving wrong set of points

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#3623]
## Version
1.6.3

## Test Case
https://jsfiddle.net/sL2np4wj/25/

## Steps to reproduce
1) Drag and drop image on canvas which actually draws Line on canvas with hardcoded Points values
2) After adding Line object , get the x1,y1,x2,y2 values using  below code 

console.log(" "+(obj.calcLinePoints().x1+obj.left)+" "+ (obj.calcLinePoints().y1+obj.top)+" "+(obj.calcLinePoints().x2+obj.left)+" "+(obj.calcLinePoints().y2+obj.top));

3) The obtained points are completely different from the original points with which line is initially drawn

4) Get the points after object modified and draw line with obtained points , you will see the line object placed at some other place since points obtained are incorrect

## Expected Behavior
1) using calcLinePoints() and adding left and top to respective points should give the right set of points so that line with new set of points drawn next time should be at the same place
## Actual Behavior
1) calcLinePoints() and adding left and top is giving wrong set of points

**Comment by ManjunathBiradar** [comment]
@asturur Please help..

**Comment by asturur** [comment]
This is not an issue. This is a personal interpretation of what a method should do.

fabricjs docs hide calcLinePoints since it is tagged as private. Is an internal method used for svg export and drawing purpouse.

If you want to know the actual canvas position of the line points after you dragged / rotated / scaled them you have to do:

var matrix = line.calcTransformMatrix();
from calcLinePoints create 2 points { x: x1, y: y1 } .....
then transform those points with the matrix

point1 = fabric.util.transformPoint(p1, matrix);

**Comment by ManjunathBiradar** [comment]
@asturur Thank you so much ....:-)

**Comment by MrHungPhan** [comment]
@asturur  Thanks u, but I reset Line coords object wrong position of line with 
line.set({x1: point1.x, y1: point1.y, x2: point2.x, y2: point2.y}).

**Comment by kashaf-ahmed-drishyaai** [comment]
> @asturur Thanks u, but I reset Line coords object wrong position of line with
> line.set({x1: point1.x, y1: point1.y, x2: point2.x, y2: point2.y}). Its only right with moved, but wrong with scaled

+1
