### ISSUE TITLE
ignoreZoom option on getPointer respects zoom level

### ISSUE THREAD

**Issue by Cyken-Zeraux** [kangax/fabric.js#3659]
## Version
1.7.3

## Test Case
https://jsfiddle.net/66jw211L/1/
Open console, click on the top or left of the circle. mousepointer 2 with `getPointer(event.e, true)` is the one that gets the right input.

## Steps to reproduce
1. `canvas.getPointer(event.e)` in an event such as `canvas.on('mouse:down', function(event){})` 

2. set canvas zoom higher than 1. such as `canvas.setZoom(3.0)`. The higher the level, the more exagerated the effect.

3. add object and output data from getPointer on the event above.

## Expected Behavior
The second option for getPointer is called 'ignoreZoom'.
```javascript
//canvas.class.js
/**
     * Returns pointer coordinates relative to canvas.
     * @param {Event} e
     * @param {Boolean} ignoreZoom
     * @return {Object} object with "x" and "y" number values
     */
    getPointer: function (e, ignoreZoom, upperCanvasEl) {
```

when ignoreZoom is true, it should ignore zoom.  When false, respect zoom. By default, using `getPointer(event.e)` should respect zoom

## Actual Behavior
when ignoreZoom is true, zoom level is respected. When false, zoom level is ignored. By default, zoom level is ignored. There is other code that relies upon this behavior, such as in `__onMouseMove`

**Comment by asturur** [comment]
I guess is a naming convention, maybe not perfect, but so old and estabilished i will not change it.
It depends what you expect you are clicking on.

The original function was returning coordinates when zoom was not introduced yet. For compatibility reasons the function was inverting the zoom transformation so that the old function would behave the same way.

What you ignore is the inverse transform of the zoom, so that the mouse pointer is not restored to plain unzoomed coordinates.

A little note on jsdoc over the function would not hurt.

**Comment by asturur** [comment]
add comment on jsdocs
