### ISSUE TITLE
event.target.originalState was removed?

### ISSUE THREAD

**Issue by tadeucaldas** [kangax/fabric.js#3660]
## Version
1.7.3

## Test Case
http://jsfiddle.net/tadeucaldas/qoaLdv2g/

## Steps to reproduce
Drag the rectangle somewhere inside the canvas so it can trigger the 'object:modified' event
## Expected Behavior
the alert should show a JSON string of the target´s original state
## Actual Behavior
the alert shows 'undefined'

OBS: this works on 1.6.7 version

**Comment by asturur** [comment]
it has not been removed, it has been  moved.
The originalState was not a documented feature but more a way to fire object:modified from a statefull parameter.

You should find the same information in the property ._stateProperties or ._originalState

**Comment by asturur** [comment]
To be more precise, something that maybe should be mentioned in 1.7.0 changelog:

http://jsfiddle.net/qoaLdv2g/1/

statefull has been moved from default true to default talse.
This because stateful and originalState collection was the only way to fire object:modified

Now object:modified is tracked by the action and originalState is no more necessary. so it has been switched to false.

I did the change since statefull was not advertised as a feature. The same process of automatic data collection is done for the cache system, also default to false.

Other than that originalState, now `_stateProperties`, does a deep clone job with the 1.7.0, making it heavier but more precise in spotting differences, before objects were referenced.

you can re enable originalState ( with the `_stateProperties` name now ) setting a boolean at canvas initialization or modifying the canvas prototype.
