### ISSUE TITLE
[Feature request] minor improvements (IMO)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3673]
Hi,

I am using more and more fabric and it's really a wonderfull library.

I am thinking about a few realy minor/very low priority feature request, and i want to know your opinion.

- In the ITEXT object, you can customize the border color when entering the editing mode, but a new "editingBorderDashArray" propertie to customise the border style could be a plus.

- in the ITEXT component when you want to exit the editing mode, you need to click outside the object in the canvas or click on the ESC key. Perhaps a click on the border (showing a "move" cursor on border hover) to select again the object could be more user friendly.

- Possibility to custom the shape of the corners (actually we can change the shape : rect or circle + color, but more customize settings could be great) it seems to me i have see something like this in the issue board but i can't find it. I want to set a white round corner with a black edge, so the controls can be visible on dark or white background.

- Have a more beautifull icon for the rotation (to replace the crosshair).

- I have seen on some online editors an interesting feature. They put a transparent area near each 8 controls so if you move the cursor a few pikels you can rotate the object. not sure if i am enough clear. If you put your cusor on a control point you gotthe stretch cursor, but if you move a few pixels you have a rotation cursor. This feature is usefull when you have so objects on the top of the canvas, with fabricjs you can't access the rotation control iy the object is on the top border of the canvas.

It's my 2 cents opinion on a few features who could be usefull.

**Comment by asturur** [comment]
Well many of this features are strictly related to editor applications.
Fabric does not want to be an editor sdk even if is really close.
It would be better if it provides more simple things that can be combined by dev to achived those things, maybe with a bit of override.

Actually corners have 5 customization properties since 1.6.2  check here: 
http://fabricjs.com/fabric-changelog at 1.6.2 version. and you can obtain more nice controls.

if you look at http://www.shutterstock.com/editor that is built on top of fabric.js with some override of course you will see nice controls, one is a graphic icon.

A lot of feature are possible, all nice, but we have to be picky on what to insert and then support.

**Comment by ncou** [comment]
Thank you for your quick answer :)

For the third point, i have found the pullresquest : https://github.com/kangax/fabric.js/pull/3128
I think the 3 first points could be a great addition for fabric.js because there is already some similar functions.

For the 4th and 5th point are more like an editor sdk need, i will investigate the shutterstock editor to see what they could do with fabric.js, and if i could override some functions.

I understand and respect the need to be picky before adding a new feature. 
Like i said this lib is awesome with or without thoses features, keep up the good work.

**Comment by vudduu** [comment]
I replace the old pull request with this one [#3729](https://github.com/kangax/fabric.js/pull/3729).
