### ISSUE TITLE
isVML function outside the class object. is that normal ?

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3711]
Hi,

I redefine the _drawControls to add a "cross shape" for the controls.

There is an error in my "fabric.Object.prototype._drawControl()" because the "isVML()" function is undefined.
I have made a copy/paste of this function, so there is no more error.

But : is it normal to have this function outside the class object ? 
=> It's defined in line 14523, and the classe extend start line 14525.
It's a bit disturbing for a newbie who want to override some functions.

PS : Are you interested in a PR for the "cross shape" ? or you don't need it in the fabric library ?

**Comment by asturur** [comment]
so i m just switching to fabric version 2, piece by piece and the isVML stuff, being a thing for internet explorer 9 or less, is going to be removed.

Regarding more controls, no, i m not interested. If you like to contribute, write a nice explanation on how you draw the custom controls, how did you obtain your own shape, and we can make it a tutorial on fabricjs.com. Is more usefull to explain devs how to do things, rather than giving many options that are never enough.
