### ISSUE TITLE
Change item property in a group  

### ISSUE THREAD

**Issue by zkrami** [kangax/fabric.js#3775]
I just started with fabric.js 
I created a group and I triend to animate a single item of it but nothing happened 
` var canvas = new fabric.Canvas("c");
         
           var rectangle = new fabric.Rect({width:200 , height:100 , fill:'red' , top:100 , left:100}); 
           
           
           var group = new fabric.Group( [  rectangle] ) ; 
          
  
           canvas.add(group);
           canvas.renderAll();
            
        document.getElementsByTagName("body")[0].onclick = function(){
           
           
           console.log(group.item(0).getAngle());
           group.item(0).setAngle(45); 
           console.log(group.item(0).getAngle());
           
           
           canvas.renderAll();
           
        };
       ` 

I downloaded the latest version of your project 
and I'm working on Google Chrome 56.0.2924.87 (Official Build) (64-bit)

**Comment by asturur** [comment]
mmm this is a caching problem

angle is not in the list of the properties that invalidate cache.
So changing it will not invalidate the group cache.

Other than that rotating an element inside a group is highly discouraged since the group dimension will not be affected from its rotation.

Please have a read here

http://fabricjs.com/fabric-object-caching

If you just started you took an unfortunate example i have to say.
if you want to rotate objects inside group, disable object caching.
Instructions in the link provided

**Comment by zkrami** [comment]
Thank you I think the problem solved

**Comment by ncou** [comment]
Will the "angle" propertie be added to the list of propoterties to invalidate the cache in the next fabric.js release ?

**Comment by asturur** [comment]
no. we should see a way to refresh groups anyway. Groups are not meant to be modified internally yet. bounding boxes do not update. you can change colors and other small things but not dimensions affecting properties

**Comment by Ivanca** [comment]
Is there a way to modify groups internally yet? I'm directly calling group._calcBounds() and this.graphic._updateObjectsCoords() to make it work but is mostly a hack.

**Comment by asturur** [comment]
not really. I did not made any progress in that direction, because is unclear to me what would be a feature and what not.
Care to illustrate your use case?

**Comment by joaojhgs** [comment]
> not really. I did not made any progress in that direction, because is unclear to me what would be a feature and what not. Care to illustrate your use case?

Just passing by this 7yo issue... I'm also currently using the _calcBounds() and _updateObjectsCoords() functions for a use case of mine, so I thought I would just reply and ilustrate the use case, it may come in hand to understand how something natively implemented would be usefull.

I'm creating a custom group where it's custom properties are used to generate other objects directly into said group, every time said properties are changed I simply recalculate the objects positions, add the ones that weren't there before and remove the ones that shouldn't be there anymore.

I also created custom controls that go into these custom properties which are in fact points on the canvas delimiting the group size and bounds to which the objects will be generated, interacting with these controls change the points and as such the group objects sometimes could be completely redistributed, making it necessary to update the group bounding box in realtime. That could only be acomplished by using these internal functions (calcBounds and updateObjectsCoords).

I understand that groups are inherently not thought of to be used in cases like this, since their "internal" objects shouldn't be changed by themselves, but reality differs from theory and most of the time when someone using fabricjs needs to group things into one entity using custom logic they will end up using an extension of the group object, and end up needing to battle against the opinionated group implementation, as  such, support for these advanced/custom implementation would be greatly appreciated for performance.

**Comment by ShaMan123** [comment]
@joaojhgs as you said this is an old ticket. A shame to stick to te old version of fabri it relates to.
v6 has all you need I believe.
