### ISSUE TITLE
text shadow on top when objectCaching is disabled

### ISSUE THREAD

**Issue by fahadnabbasi** [kangax/fabric.js#3794]
## Version
1.7.6

## Test Case
https://jsfiddle.net/fahadnabbasi/rznzLepm/

## Steps to reproduce
Add a text element on canvas with fabric.Object.prototype.objectCaching = false;
and you will see that the shadow is coming on top of actual text
## Expected Behavior

Shadow should show below the actual text element

## Actual Behavior
Shadow is coming on top of text

**Comment by asturur** [comment]
WEIRD!

it happens only with offsetY < 0.

guess if is a fabric or canvas bug.

**Comment by asturur** [comment]
Can you check what happens with rects?

**Comment by fahadnabbasi** [comment]
works fine with rectangles

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/24324501/e7f529ae-1187-11e7-9387-85d2a8e3d936.png)

ok is not a `bug`.
the problem is that if the lineheight is small and the shadow offset is high, the shadow of line 2 is over line 1. this is `normal` and can be avoided just with caching.

Nothing i can do here. You should enable caching.
