### ISSUE TITLE
Text rendering issue (fill color and maybe others)

### ISSUE THREAD

**Issue by FeaRCODE** [kangax/fabric.js#3850]
## Version
1.7.6 (to my knowledge and quick tests 1.6.7 doesn't have this issue (not sure which are effected))

## Test Case
http://jsfiddle.net/Da7SP/519/

## Steps to reproduce
1) Add text to canvas
2) Attempt to change fill color
3) Resize text after background changes (you will see THEN it changes)

## Expected Behavior
1) Fill color should change

## Actual Behavior
1) Fill color doesnt change until you resize it (even canvas.renderAll() doesn't fix)

**Comment by ncou** [comment]
Hi,

It's related to the cache option who has been added in the 1.7.0 version.
Please read this article : http://fabricjs.com/fabric-object-caching

You have 3 options :
1)
In your case if you use `.setFill("white)` instead of `.fill = 'white`" it will work because the cache will be invalidated.
2)
on your object you add the parameter `statefullCache:true` and there will be a check on the cache related properties (fill, stroke....etc). so the cache will be invalidated
3)
You disable the cache on your object using the parameter `objectCaching:false`.

The first solution is the better from my point of view.

Close the ticket if it's ok for you.

**Comment by FeaRCODE** [comment]
You know, i didn't even think about the object caching, i just thought setting the fill like that would simply work. Thanks for your response, and that's good for me!
