### ISSUE TITLE
Removing setSelectionStyles from text elements when fill color is set

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3929]
Hi

I was wondering if there is a way to reset the selection styles applied to text?

## Version
1.7.9

## Test Case
https://jsfiddle.net/human_a/gtc3w57b/

## Steps to reproduce
First, click on the "SET FILL COLOR", it will do as expected, adds a fill color to the test element. Then select a word inside the text element and click on the "SET SELECTION COLOR", again does as expected, but finally click on the "SET FILL COLOR" button again to set a fill color on the entire text overriding the selection color, but it does not work, in fact, the set fill color becomes useless.

## Expected Behavior
When setting the fill color, it is expected to override the selection fill color applied, or there should be an option to rest the selection fill color.

**Comment by asturur** [comment]
So in the new branch, the 2.0.0beta, while not present, is supposed that:

the dev will get:

a method to flatten the style: if all text has the same fill color in style, the style will become the main property and style will be deleted

a method to clean the style: style properties equal to main properties will be removed

a method to delete properties in the style.

You will be able to achieve the effect either setting the work do same color of background ( and calling the cleanStyle method ) or calling the delete properties on that range / full text.

it won't be automatic with setting a color. In your application code you will pick the strategy you like more.

**Comment by asturur** [comment]
after those methods are ready, i can ping you, if interested in having them in 1.x branch you can backport them and open a pr.

**Comment by human-a** [comment]
Thanks for the reply, so right now there is no way I could see the code or maybe you could share a function from it for me so that I could use it right now?

Also, any estimations when version 2.0 reaches the public access?

**Comment by asturur** [comment]
2.0 is the current master branch, is public and is also on npm. is just in beta.
In beta means that some methods may disappear or change function arguments, so if you are working on a project that involves public access and deadlines, you may not want count on it.

It works good and is called 2.0 because some api changed.
The text is completely new: Text support all that Itext does but without editing abilities, it also now support properly multibyte characters ( emoticons and asian language text ) composition has been fixed ( macosx popup, chinese and japanese input ).

Other than that the new filtering engine is way better than the old one.

And shapes with transform matrix controls has been solved.

Has soon as i can pack those things in i ll try to release it.

**Comment by human-a** [comment]
Wow, that is super exciting news, can't wait to implement it in my project and give it a try.
What about webGL support, is it also added?

**Comment by asturur** [comment]
WEBGL is used for image filtering now where available.
Full webgl canvas is not supported for now, no idea if i will ever be able to do it.
There are ongoing optimization for the general canvas2d render, plus a different render to use during toDataurl to get as best as possible final renders.

I have no idea if webgl rendering is good for painting fabricjs generally.

**Comment by human-a** [comment]
I also agree the entire webGL support is not required, the image filtering and toDataurl optimization would do it. [glfx](http://evanw.github.io/glfx.js/) is a good example of what is needed for image processing with 2D webGL.

**Comment by asturur** [comment]
you can give a check to the new text and filters here ( there are just little filters here, but you can get an idea of the speed )

https://www.shutterstock.com/it/editor/image/418367578

the filter engine has been rewritten by me and another brave guy during work time but is being opensourced by the company. We took inspiration by other open filtering engines. ( glfx to learn what to do, but then we went on our own ).

**Comment by human-a** [comment]
Great job there, I have worked with it before, I love how fast and responsive image filters are. I also love the new text, you mentioned it's like iText but NOT editable?

**Comment by asturur** [comment]
no we get both text, itext and for now also textbox.
Many of itext graphical capabilities ( styles ) are transferred to text. so that if you need to paint a static text, you can still use style for it.
The whole text is generally slower since it has to measure more things when you actually change text or fontSize, but supports kerning and is more mantainable, at least for me.

Ident, bullet list and glyph substitution are features developed for the company that for now stays there. I have no really strength to support everything anyway.

**Comment by human-a** [comment]
Thanks for the info, one last question if you don't mind, I see that the fabricJS canvas used in shutterstock supports bleeding (you can see, select and edit objects even if they are bleeding out of the working area of the canvas) Is this a new feature in 2.0 or have you done something custom, and if so could you point in the right direction how to implement this system in fabric projects, I seem to have problem wrapping my head around implementing the infinite canvas system with fabricJS.

**Comment by asturur** [comment]
The bleeding is just the overlayImage, or an 'after:render' event that paints a transparent mask over everything but not what we consider the page area.

there is a new property that is canvas.vptCoords that tells you where your viewport extends in absolute coordinates. that helps you understanding at small zoom or high zoom what are the main 4 corners of your view.

if you are at zoom 1 you are watching a rect that extends from 0,0 to canvas.width,heigth.
if you zoom 2, you are probably watching from 0,0 to canvas.width/2, heigth/2. and so on. with this info we paint a mask.

**Comment by human-a** [comment]
Thank you very much, it makes sense now to me.

**Comment by asturur** [comment]
@human-a https://github.com/kangax/fabric.js/pull/4060  this should solve. I do not think you need instructions. read the code, or read the added tests.

I ll update text docs in some way to make a big tutorial if i manage.

**Comment by human-a** [comment]
@asturur Thank you very much, it was a much-needed option for us, thanks for letting me know.
