### ISSUE TITLE
support off screen?

### ISSUE THREAD

**Issue by jsonformat** [kangax/fabric.js#3941]
Such as the title
docs, hard to find!!
My basic ability is not strong, so read source code difficulty
Can you tell me?
Find what I want in it?
thanks!

**Comment by asturur** [comment]
Please explain yourself better.
I do not understand.

**Comment by jsonformat** [comment]
Similar: `document.createElement('canvas')`
fabricjs: api?

**Comment by jtara** [comment]
Actually, I just had the same thought, and a search led me to this Issue...

Is there a way to have Fabric render to an offscreen canvas?

If not, I suppose one could render to a hidden canvas? Any gotchas because it is hidden?

I am looking for a way to scale-down (or resample) a sketch made in free sketch mode. I want a high resolution on-screen for appearance - I use retina mode (and the user can zoom using jquery.panzoom, which works well), but need a lower resolution for some image processing. 

I've looked at various ways to resample, but it seems to be perhaps the most straightforward is simply to re-render the object list onto an off-screen or hidden canvas.

**Comment by asturur** [comment]
yes and no.

there are many ways to do this thing.

you could consider send the json up to the server and render with nodejs and node-canvas.

you could consider export to svg and turn svg to image on the server

you could process on the client with webgl ( depending what is your processing )

export the canvas to a smaller one using toDataUrl

i do not think using jquery panandzoom is a good idea, what is wrong with mouse events and internal viewport transform zoom?

**Comment by jtara** [comment]
Thanks for your comments.

The "server" is actually in a hybrid mobile app (NOT PhoneGap - Rhodes - and code is in Ruby, not JS, though they have just added a node server which I have not tested yet). The image processing is done in C with code generated by MatLab Coder.

I wound-up creating an offscreen canvas with document.createElement('canvas'). For a simple test, I set the width/height to the onscreen canvas width/height *2 and set scale to 0.5. It's about 80mSec on iPad Air2 to scale image down to 768x714 and quantize to 1-bit, so quite acceptable.

``` javascript
      var offScreenCanvas = document.createElement('canvas');
      offScreenCanvas.width = sketchCanvas.width / 2.0;
      offScreenCanvas.height = sketchCanvas.height / 2.0;
      var offScreenCanvasCtx = offScreenCanvas.getContext('2d');
      offScreenCanvasCtx.scale(0.5, 0.5);
      offScreenCanvasCtx.drawImage(sketchCanvas, 0, 0);
      var sketchImageData = offScreenCanvasCtx.getImageData(0, 0, offScreenCanvas.width, offScreenCanvas.height);
```
Maybe above will help *jsonformat*.

I use jQuery.panzoom because I have to pan and zoom more than just the canvas that fabric.js sketches on. There is a background grid SVG placed behind the canvas, and more layers behind that can be revealed with results from the image processing. All need to scale/pan together. jQuery.panzoom has worked well, with the caveat that we have to do a modal zoom to avoid stray marks. (e.g. you are panning/zooming, or you are drawing...) It is responsive, and everything is sharp when zoomed-in.

FYI, I am rewriting this from native iOS code targeted for iPad only to a hybrid mobile app for iOS/Android phones and tablets and Windows desktop. fabric.js has worked out well!

[SpatialVis.education Home](spatialvis.education)

Thought you like to know one more use case!

(current App Store app is old native app - and has horrible fuzzies when zoomed.)
