### ISSUE TITLE
centeredRotation does not work on set('Angle', angle)

### ISSUE THREAD

**Issue by ImTheMark** [kangax/fabric.js#3963]
## Version
2.0.0-beta1

## Test Case
http://jsfiddle.net/c43dop09/

## Steps to reproduce
Draw a canvas object with property centeredRotation: true
Rotate the object using the rotation handles.
Rotate the object using the set('Angle', angle)

## Expected Behavior
Rotating the object using the rotation handles rotates the object from the center.
Rotating the object using the set('Angle', angle) method rotates the object from the center.

## Actual Behavior
_Rotating the object using the rotation handles rotates the object from the center. (NO ISSUE)_
Rotating the object using the set('Angle', angle) method DOES NOT rotate the object from the center. The rotation includes the rotation handle(cursor?) when computing for its center.

**Comment by ncou** [comment]
Hi,

I think you need to use the 'setAngle()' function not the .set('Angle',xx) function.
It's working with setAngle(), because it force the "originToCenter" while the setter doesn't do it or made a reset (i don't remember).
check the other threads there is a more complete explanation.

Here is a working fiddle :
http://jsfiddle.net/c43dop09/1/

**Comment by ImTheMark** [comment]
I do find it strange that two methods that sets the same property have different behaviors.
Anyways, thanks for the information and help. It's greatly appreciated!

**Comment by asturur** [comment]
setAngle is bad named, and gonna be changed.
setAngle is an emulation of what you would do rotating the object manually.
the angle property rotate the obejct on the current origin point if i recall correctly.

i do not like this ambiguity aswell and i have no clear grasp of why it happens since the draws are all center based.
