### ISSUE TITLE
Fabric JS Canvas text issue on iPhone

### ISSUE THREAD

**Issue by vipulmishra341** [kangax/fabric.js#4009]
I have developed an website for customizable invitation using Fabric JS and knockout JS on Magento community version. The invitation product working fine on Android and all windows/Mac version browsers but not on iPhone. As soon as all the fonts are loaded on iPhone text is broken in multiple line, overlapped and misplaced.

Please find the below screenshot URL for the issue on iPhone.
https://www.awesomescreenshot.com/image/2585423/53dbaae3b74b7f965897c2f9d295001d
https://www.awesomescreenshot.com/image/2585427/ce200b1c2d2fbdc088a053c5c84ad84d

Website URL and product URL (click on personalized button):- http://candlebark.testingdemo.net/wedding-invitations/anchoredinloveweddinginvitation.html Popup U/P:- test/test@123

The same product URL is working fine on iPhone simulator and on browser stack.

**Comment by asturur** [comment]
i do not have an iphone to try it.
Please reproduce a breakage situation in a very simple jsfiddle with just a textbox

**Comment by kelvin-im** [comment]
Having a similar issue above with with using fonts Open Sans and RIVERHACK in Safari 10.1. This issue seems to come up on first load, or if the page is reloaded. The i-text comes up properly on occasion, but often I end up with the question mark blocks on some if not all i-text objects. See codepen and screenshots below:

https://codepen.io/kelvin-im/pen/xrRNEx/

![safari_2](https://user-images.githubusercontent.com/26411642/27242700-6d39be44-52ac-11e7-8649-5a1e003b01b0.png)

![safari_1](https://user-images.githubusercontent.com/26411642/27242640-25f2ffa0-52ac-11e7-9934-24d71c715cef.png)

**Comment by Taral-Patoliya** [comment]
I am also having exact problem wit ipad and iphone.

**Comment by Taral-Patoliya** [comment]
When can we accept this issue to be resolved? as this is very crucial and a show stopper issue.

**Comment by asturur** [comment]
Is not about accepting it or not.
Custom fonts works. When they do not work is because they have not been properly loaded on the canvas.
Can you share the code with which you are loading fonts?
