### ISSUE TITLE
[BUG] Strang moving while resizing

### ISSUE THREAD

**Issue by neilliang** [kangax/fabric.js#4028]
Sorry English is not my native language. I'll show video to explain the bug.

I created a very simple fabric object like bellow

```
<html>  
<head>  
    <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="fabric.js-1.7.13/dist/fabric.min.js"></script>
    <title></title>
</head>
<body>
    <div id="canvasContainer">
      <canvas id="c" width="400" height="400"></canvas>
    </div>	
<style>
	#canvasContainer {border: dotted gray thin ;width:300px;}
</style>
<script> 

//public function define
fabric.Object.prototype.init_setHandls = function() {
	 this.borderColor = '#03a9f4';
	 this.cornerColor = '#03a9f4';
	 this.padding = 0;
	 this.cornerSize = 15;
     this.setControlsVisibility({'mb': false, 'ml': false,'mr': false,'mt': false});
};
(function(){
	var canvas = this.__canvas = new fabric.Canvas('c');
	var rect =  new fabric.Rect( {
		left : 100, 
		top : 100, 
		fill : 'red', 
		width : 80, 
		height : 80
	});
    //init handls' style
    rect.init_setHandls()
	canvas.add(rect).setActiveObject(rect);	
})();

</script>
</body>
</html>
```
Here is the bug video, any idea?  

Youtube: https://goo.gl/1NiwoP

**Comment by Tsunami2069** [comment]
I could be wrong but i believe that is normal behavior.

Since your rectangle has an origin point on the top and left and it also has that option to maintain the ratio between height and width (lockUniScaling), resizing the image will only change it in a diagonal manner... But if you drag the mouse to the other side of that origin point, the image will change to that side as if you had dragged it to its center and then to the bottom left.

**Comment by asturur** [comment]
there is a lockScalingFlip property you can disable
