### ISSUE TITLE
violation warning in console devtools

### ISSUE THREAD

**Issue by sandor** [kangax/fabric.js#4039]
Hey Guys i am getting a lot of this warning in chrome:

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

Should I be woried about?

**Comment by p3ndu** [comment]
Hi,

This is related to: https://github.com/kangax/fabric.js/issues/3869
There should be a fix in the near future, I am waiting for it also.

Regards,
Alex

**Comment by sandor** [comment]
Thanks Alex - will wait for the fix...

Side question only: Could this be a reason why my electrton project is making some problems (not freezing but denying to quit or reload after invoking a farbric.js function)? Having my problems with and is hard to debug... Sorry if this is inappropiate here!

**Comment by asturur** [comment]
If you are gettint that violation is because we are adding a non passive event. we can switch to passive event once we know if someone will need to cancel scrolling during event handling.
So i think it needs a bit of thinkering with a configuration parameter or checking alternatives.

You should not be worried about it, unless you are executing heavy stuff on mouse down.

**Comment by asturur** [comment]
That message says in small words:

Me, the browsers, cannot start scrolling on touch down because there is an event handler there.
That event is not declared as passive, so it retains the possibility of cancelling scroll during the event handler, so i cannot start scroll until the whole event is executed. This could create some shuttering in scroll start.
It would be better if you would declare it as passive, so while i handle your event, i anyway start scrolling.

Is silly from chrome from my point of view.

**Comment by sandor** [comment]
@asturur Thanks Andrea! Hard for a beginner to get all this stuff :-) Is there a way to reach you outside this github issues? Don't want to abuse this place... Thanks!
