### ISSUE TITLE
Canvas clipTo for paths

### ISSUE THREAD

**Issue by drave** [kangax/fabric.js#4040]
## Version
1.6.0+

## Test Case
http://jsfiddle.net/o9f4dqjn/56/
http://jsfiddle.net/o9f4dqjn/55/

## Steps to reproduce
Clip canvas to a path with fabric 1.5.0:
Works properly @ http://jsfiddle.net/o9f4dqjn/55/

Clip canvas to a path with fabric 1.7.13:
Does not show elements at all @ http://jsfiddle.net/o9f4dqjn/56/

## Expected Behavior
Clipping to a path working as in 1.5.0, showing elements within clipping area

## Actual Behavior
Objects are hidden when inside clipping area, but can sometimes still be dragged / resized etc.

**Comment by ncou** [comment]
Hi,

1)
There is a problem in your second fiddle, you point to an external lib of fabric.js v1.7.11 but you also add the v1.5.0 in the internal lib of the fiddle.

2)
Since v1.7 there is a cache mechanism, read more here.
http://fabricjs.com/fabric-object-caching

if you set objectCaching to false on the path it will work, because clipTo work with path and not image (used for the cache). Disable the cache for your clipped path and it will work.
http://jsfiddle.net/o9f4dqjn/57/

Close the ticket if it's ok for you.
