### ISSUE TITLE
How to initial object index level?

### ISSUE THREAD

**Issue by david0116** [kangax/fabric.js#4085]
I tried to bring all the texts to the top layer level of the canvas. I've tried several ways but still not working. Here is the demo https://jsfiddle.net/x2w120e0/ . 

There are only 2 of 4 texts finish the job. Any idea?

**Comment by asturur** [comment]
https://jsfiddle.net/x2w120e0/2/

is a standard javascript problem.
While looping in foreach you are changing the underlaying array so that text is in position 0,1,2,3,

you loop over 0, move text to top.

the next iteration would go over 1, but since 0 is moved and array modified, the second in position is 2.

1 does not get processed and stays at bottom.

Check updated fiddle. is not the right solution but it makes the idea.

https://jsfiddle.net/x2w120e0/2/

This other solution is better

https://jsfiddle.net/x2w120e0/4/

you ask for objects of type 'text' a new array is created, so when you send them to top, the array that you are looping for is not touched.

**Comment by david0116** [comment]
Alright I got it. Sorry I thought it's a fabricJS bug. Thanks for detailed explanation.
