### ISSUE TITLE
Font leading in TextBox object in v2

### ISSUE THREAD

**Issue by gcox** [kangax/fabric.js#4112]
~~Sorry for the potential duplicate question. There are a ton of issues and comments that make some sort of reference to leading, but it isn't clear to me from reading through them all whether kerning is actually supposed to be properly supported in the most recent beta of v2. It would appear that it isn't fully supported, but many of the comments regarding v2 seem to suggest it is, but that has not been my experience.~~ **Update**: Sorry, was referring to the wrong typographical term. I should have referred to this as `leading`, the vertical space between lines.

Is proper leading supposed to be supported by fabric? 

From my tests, using Oswald Regular (https://fonts.google.com/specimen/Oswald) and v2 beta 3, leading is not being handled. The line spacing is noticeably tighter than it is supposed to be.

@asturur Would you mind confirming one way or the other whether this is actually supposed to be supported?

**Comment by asturur** [comment]
No is not. This can be supported once we have a way to measure the real height of a font.
For now the height is exactly fontSize. And is a wrong assumption most of the time.

The biggest change that has happened in v2 is that a character has its own bounding box.
The way i plan to introduce proper font measurement is that there will be a method in fabric, probably a sub section of one we already have that well be called to measure a char and a couple of char and must return some information.

This method will be written with override in mind so that you can plugin in any js font library available out there and measure the char your own way and get better support for dimensions.

Fabric is already a big library with too much code and cannot support everything.

**Comment by asturur** [comment]
unicode support is already working like that. We have a graphemeSplitter function that you can override with one more complex that support all emoji and language. I picked up one that does the bare minimum work for fabric.

**Comment by gcox** [comment]
@asturur Actually, for my particular situation, knowing that the line height is equal to the font size in pixels is enough for me to get around the problem I'm running into.

**Comment by asturur** [comment]
the line height is fontSize * lineHeight

you can follow the math easily reading the code

**Comment by gcox** [comment]
@asturur I see that now. Thanks for the help and clarification!
