### ISSUE TITLE
minScaleLimit not applyed for TextBox object

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4223]
Hi,

Shouldn't the minScaleLimit parameter also be taken into account when you scale down the object ?
Is that a bug or a wanted behaviors ?

Jsfiddle
https://jsfiddle.net/wq3pyhhu/20/

**Comment by asturur** [comment]
Explain because i do not understand.
minScaleLimit is an half feature that i think was introduced because the risk of making an object too small make it then not usable anymore.

What is the problem actually?

**Comment by ncou** [comment]
I added the jsfiddle in my first post. it seems like this parameter is not taken into account when you scale a textbox object.

**Comment by asturur** [comment]
I m sorry i read the message and not the title.
i ll check.

**Comment by asturur** [comment]
I ll update the docs saying that ihave no clue of what to do with this minScaleLimit.

you can set minScaleLimit, but by design the value you set is overriden as soon as you set width and height.
Basically this minScaleLimit is a dynamic value used to avoid the object to go under one pixel during scaling

If you set in the constructor of the textbox it gets deleted as soon as textbox calculates the width.
If you set it later it works for the vertical scale, but after the first wrapping, the value get ovverridden by the new one.

I should clearly state that minScaleLimit is not a feature is used by fabric and nothing else.

**Comment by asturur** [comment]
i gave a stab at removing the changes for minScaleLimit. i see no reason for them
