### ISSUE TITLE
Rotate change the position of object

### ISSUE THREAD

**Issue by SzabZol** [kangax/fabric.js#4245]
Hi!

When I rotate an object on canvas, its position changed. And I can't use center origin, just left/top.
Can you help me? Any idea?

http://jsfiddle.net/ndvpbbrq/1/

Thanks

**Comment by asturur** [comment]
What is exactly your problem?
Position change with rotation. That is right and not going to change if you want a rotation around the center.

**Comment by SzabZol** [comment]
Yes, but I want to save the left and top offset of image to database for later use. So these are false data.

**Comment by asturur** [comment]
Those are the data you need to render the image in that position.
Or they would not be there

Please add a complte explanation of why you think this is wrong, add a failing case fiddle were a fabricjs feature is failing because of this and we can track it down.

For any other help question you should refer to stack overflow.

**Comment by ncou** [comment]
There are not "false data" it's a different referential so the coordinates are differents.
You can use the getPointByOrigin function to calculate the value given a top/left referential.
 
Here is an example.
http://jsfiddle.net/ndvpbbrq/2/

Close the ticket if it's ok, else open a stackoverflow question with more informations, i will try to help.
