### ISSUE TITLE
Text Box Group Stretching on Selection

### ISSUE THREAD

**Issue by mhaseeb-seecs** [kangax/fabric.js#4259]
## Version
1.7.17

## Test Case
https://jsfiddle.net/0txdL8bk/

## Steps to reproduce
- Created a Canvas.
- Added 2 Text Boxes
- Grouped Text Boxes
- Re render and Select the group

## Expected Behavior
Text Boxes should be grouped and remain un stretched 

## Actual Behavior
Text Boxes are grouped but stretched

**Comment by asturur** [comment]
this is one of the reasons why we rewrote text support and switched to 2.0

this will not be fixed in 1.x while should be fixed already in 2.0

**Comment by mhaseeb-seecs** [comment]
That was beta version so i was hesitating to use it. Updated to 2.0 resolved that issue instantly worked like a charm 👍 Thanks...

**Comment by asturur** [comment]
look in the 2.0 beta is as bugged as the stable. is called beta because is still under tweaking and changing maybe.

beta7 is coming and i hope is last one

**Comment by mhaseeb-seecs** [comment]
thanks. totally appreciate you help.

**Comment by adilmas13** [comment]
I am using the latest fabric version as of date and this issue still persist... are they any solutions out there besides the ungroup solution... need help asap

**Comment by asturur** [comment]
this is super hard to reason about.

Imagine you have fabric 4 and you write your custom controls for group. You drag a corner and instead of changing group scale, you change group width and height. that is fine.

you can enlarge textboxes width of the same amount, fine.

but you have also to recalculate their position relative to the group and that is the hard part.
