### ISSUE TITLE
Third object added to activeSelection doesn't fire object:selected

### ISSUE THREAD

**Issue by jparkrr** [kangax/fabric.js#4343]
## Version
2.0 beta

## Test Case
http://fabricjs.com/events

## Steps to reproduce

1.  Select two objects
2. Shift+click on another object to add it to the selection

## Expected Behavior

object:selected fires

## Actual Behavior

object:selected doesn't fire

**Comment by asturur** [comment]
the idea, that i m putting down in a doc since yesterday, is that the object fires selected on itself, and the canvas will fire selection:updated

selection:created and selection:updated will be the main event to listen for, while object:selected is set as deprecated. (it was fired just on single selection before)

**Comment by asturur** [comment]
continue on #4336
