### ISSUE TITLE
ToDataUrl() and object selection issue

### ISSUE THREAD

**Issue by tgynther** [kangax/fabric.js#4344]
## Version
1.7.15 to 1.7.19

## Test Case
http://jsfiddle.net/tgynther/agp4k95c/

## Steps to reproduce
1. Run fiddle and select green rectangle. Problem occurs.
2. Comment out ToDataUrl() from objectsGroup and rerun fiddle, select green rectangle

## Expected Behavior
Object should be selected with aligned controls/border

## Actual Behavior
Object selection is misdrawn

![image](https://user-images.githubusercontent.com/13852765/30799397-6831512c-a1e5-11e7-931a-14843cb5018c.png)

**Comment by asturur** [comment]
http://jsfiddle.net/agp4k95c/6/

Hello @tgynther,
the problem is in how you create the activeGroup.

There are 2 things, one is that i m not sure the activeGroup can be used with one group, the other is that the activeGroup needs a reference to the canvas to handle zoom and and other stuff.

Infact the fiddle works fine with my added change or with removed zoom.

Creating a selection from code is one of the most weird part of fabric, that is why with 2.0 we are trying to make it simpler.
