### ISSUE TITLE
Bug with scaleToWidth and zoom in beta 2

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4346]
## Version
2.0 beta 6 or 7

## Test Case
http://jsfiddle.net/z7xfhf3k/1/

## Steps to reproduce
Check pos and size of blue rectangle, then comment line two (that set zoom at 0.5), the position and size is not the same. When zoomed the position & size are incorrect.

## Expected Behavior
To get correct behavior just use fab 1.7.15 in the same jsfiddle. You'll see size and pos are correct with or without zoom.

## Actual Behavior
The size and position is not correctly affected by the canvas transformation (I guess).

Thanks for your help & time!

**Comment by blobinabottle** [comment]
(and same with scaleToHeight()).

**Comment by asturur** [comment]
I ll check how those functions changed.
I do not think they are supposed to be influenced by zoom.
If you want an object to be big 100px you mean 100px of the canvas with no zoom, as an absolute reference.

i ll give it a look.

**Comment by asturur** [comment]
http://jsfiddle.net/z7xfhf3k/2/

So the function behaves the same, respecting the viewport transform.

The visual difference is that being canvas.requestRenderAll async, you were getting the render of the .add command executed after the scaleToWidth command.

the function scaleToWidth does not render and so you were simply not seeing the changes in the screen.

If i add a renderAll, i see the same exact behaviour.

About respecting the viewport or not, scaleToWidth uses getBoundingRect that has a paramenter to be used with or without viewport. So i m adding the same parameter to scaleToWidth so that the output can be chosen with or without viewport.

**Comment by blobinabottle** [comment]
Ah cool! Thanks for adding viewport param!
