### ISSUE TITLE
Circle objects fully within another circle object are not being detected by isContainedWithinObject

### ISSUE THREAD

**Issue by rockerBOO** [kangax/fabric.js#4353]
## Version
2.0 beta 7

## Test Case
https://jsfiddle.net/rockerboo/s3sckp9f/2/

## Steps to reproduce
Drawing a grid of circles with a larger circle overlapping. Use the larger circle to see if the smaller circles inside of it. Then remove the smaller circles which are contained within the larger circle.

## Expected Behavior
All circles contained in the larger circle should be identified and removed from the canvas.

## Actual Behavior
There are circles that are within the larger circle that are not being removed. All circles clearly fully inside the larger circle should be removed.

**Comment by asturur** [comment]
https://jsfiddle.net/s3sckp9f/3/

Every time i fall in the same trap, i start to debug this issue and i realized the problem is always the same.

getObjects() return the direct reference of canvas objects.
Initiating a forEach cycle and removing objects on the fly is going to modify the same array you are iterating and as a result you skip iverating over some of them.

If you make a copy of getObjects() using .slice(0) you are ok with it.
