### ISSUE TITLE
Scaling events not being fired for elements/nodes inside a selection being scaled

### ISSUE THREAD

**Issue by iongion** [kangax/fabric.js#4382]
The events for scaling are not passed to the children that are part of a selection.
For encapsulation, I also put the logic for re-scale inside a custom element:
```
const Element = fabric.util.createClass(fabric.Group, {
  type:  'data-label',
  lockScalingFlip: true,
  initialize: function (options) {
    const updateSize = (e) => {
      console.debug('Element is scaling', e);
    };
    this.on('scaling', function(e) {
      updateSize();
    });
  }
});
```

Desired, when scaling:
- you expect scaling is called whenever the object scale props change

Reality, when scaling:
- a single object, the element receives `scaling` event and that is great
- multiple objects, the elements in the selection do not trigger any `scaling`

- Is this intended behavior ?
- How would one go to be able to have scaling being triggered when scaling occurs ?

**Comment by iongion** [comment]
The fiddle https://jsfiddle.net/eL5nLk9k/1/

**Comment by asturur** [comment]
This is an `intented` behaviour, meaning that it works like that and there is no much reason to change for now.
Since now the ActiveSelection has been well differentiated from group class, may be a feature, but would break again the api in some soft way.

Unsure about that.

The same happens for moving, scaling, rotate... and rotate is not even easy to handle since when you rotate a multi selection you are actually moving and rotate objects.

When you are scaling a multi selection that contains rotate objects, you are both scaling and skewing and moving objects.

Going back to your use case:

So when you scale a multiselection the element inside are visually transformed but untouched at properties level.
They get scaled when the multiselection is dissolved.

Let me think.... if you wanted to fire it you could on fabric 2.0:

Extend the ActiveSelection class, at initialize bind an event on scaling as you did in your example, during your scaling event  do something like 
```
this.getObjects().forEach(function(object) {
  object.fire('scaling', opt);
});
```

where opt is the first argument of your scaling function.

The object will fire the event but will not have scale modified and if you are trying to calculate their actual size you will have to use the group properties too.

Please if you need more help open a SO question and leave the link here.
