### ISSUE TITLE
Inconsistent rendering of SVGs in fabric.Image objects

### ISSUE THREAD

**Issue by kputh** [kangax/fabric.js#4393]
## Version
2.0.0-beta7

## Test Case
https://jsfiddle.net/nwkacqdb/

## Steps to reproduce
Try to load an SVG file using `fabric.Image.fromURL`.

## Expected Behavior
`fabric.Image` should render SVGs properly, and identically across all browsers.

## Actual Behavior
The SVG is rendered in Safari 11. It does also render in Chrome 61, albeit at a different size. And it does not render in Firefox 56, lacking any error message in the JS console.

**Comment by kputh** [comment]
It would be helpful, if the documentation listed compatible image formats for `fabric.Image.fromURL`.

**Comment by blobinabottle** [comment]
You should load your svg with the correct method:
https://jsfiddle.net/nwkacqdb/8/

**Comment by kputh** [comment]
Sorry, I don't want to _load_ an SVG, I want to _reference_ it. In SVG it looks like this:
`<image xlink:href="firefox.jpg" x="0" y="0" height="50px" width="50px"/>`

**Comment by asturur** [comment]
The issue has been described somewhere else here

![image](https://user-images.githubusercontent.com/1194048/31927892-461079a2-b896-11e7-8390-2b56fd72da00.png)

the svg is lacking any kind of width and height.
Firefox will render it on the DOM, inspecting the container, but since there is no container when rendering offscren, he will just not render it.

I refreshed a bug in firefox asking for behave like the other browsers but they said is against the specs. https://bugzilla.mozilla.org/show_bug.cgi?id=700533#c28

https://github.com/kangax/fabric.js/pull/4324  this recent PR could work as a solution for you.

**Comment by asturur** [comment]
let me know if #4324 solved for you
