### ISSUE TITLE
Losing text style when character changing line 

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4398]
## Version
2.0 beta

## Test Case
https://cl.ly/0b1p0S1I2e08

## Steps to reproduce
It's in kitchensink but also in our app. At some point while editing text you loose the format. In the video you clearly see it keeps the position of character that's not the correct one for the style.

## Expected Behavior
Keep style for the character even if the character change line or position.

## Actual Behavior
Style is lost when character change line or position.

Thanks for your help

**Comment by asturur** [comment]
i should make one of those for fabric.IText

![q3cug29](https://user-images.githubusercontent.com/1194048/31929850-b70f4c44-b89d-11e7-8b71-b31561ed7b4a.gif)

**Comment by blobinabottle** [comment]
I'm sorry I have another one ... Don't hit me :-)

https://cl.ly/2o0L1X2u123z

If you select a range of common styled text, fabric uses the default style. But if you select a range into a styled text it's ok.

**Comment by asturur** [comment]
working on the first one.
The second one is more a product decision to take.
Fabric has no concept of current style.
It pick it up from neighbour chars.
This could change, but i have no idea what is better.

**Comment by asturur** [comment]
ok i think i fixed. Please give it a look better.
There was also another bug that was entering newlines was shifting text down.
Strange you did not notice.

**Comment by blobinabottle** [comment]
Regarding the second bug: wouldn't be a good idea to take the style of the first character after the cursor? It seems to look at the character before... What do you think? Or if a selection is currently made, use the style of the first char of the selection?

**Comment by asturur** [comment]
it could look at next if one is missing, but would not change the fact that if you select everything of one style segment you loose it.

I definitely have difficulties calling it bug, not because i do not want to fix it, but because there is no clear indication of how it should work.

Effectively if you are selecting a range, and putting other text in place of it, taking as style the first of the range could be an idea. I guess is a feature/improvement request. If you agree could you open a separate issue for it?
