### ISSUE TITLE
Beta 8

### ISSUE THREAD

**Issue by specialkk** [kangax/fabric.js#4422]
Hey, just wondering when the next beta is getting published. I've been getting used to them coming out roughly every month, but it's the end of the month now and I can't yet use some of the fixes that have been added since the last beta.

Sorry to ask for ETAs :P

**Comment by asturur** [comment]
trying to fix a webgl filter and release an rc directly.

**Comment by AvaelKross** [comment]
just a small note on webgl issues.. I'm seeing strange behavior when i'm trying to apply filters to images that bigger than 2048x2048. In safari, the image just disappears. In chrome, only left-top corner 2048x2048 in size is shown(but with a filter!), all other area is cut off. I see it's a default value and i can change it, but we allow users to upload images of almost any size.. is there a way to increase this value on the fly? And I guess it's better to raise an error if image size is bigger than 'webgl canvas' size, instead of this inconsistent behavior.. we had to turn off webgl filtering for now because of that

**Comment by asturur** [comment]
You should just really read the docs:
http://fabricjs.com/fabric-filters

please read this page and let me know if some other information is missing.

**Comment by c-gross** [comment]
HI, sorry to jump in this topic but I don't want to raise an issue since I only have a short question to the beta.

I created a product configurator with fabric.js 2 years ago with some updates until now. Next year I want to build a new better version. Because adding not planed features is getting abit dirty.

My question is what do you think when we have fabric.js 2 stable and ready for production use? Are still code breaking changes coming with the next beta versions or could I start with the beta?

**Comment by asturur** [comment]
No breaking changes are planned.
Actually stopping 2.0 release are nodejs code not working as it should, and dynamic resize filter with webgl.

2.0 is as stable as 1.7 regarding bugs.

next breaking changes are planned for patterns and gradients maybe.

clipTo function is marked as deprecated and that means that at next major version will be removed. ( 3.0 )

i ll try to follow semver strictly.

**Comment by c-gross** [comment]
Ok that are good new. Then I can start next year directly with 2.0. Only thing, I'm using gradients but not that much so that should be fine. 

But clipTo is something very important. I saw the changelog comment ".clipTo is deprecated, please stop using it, i want to do something better." Is something better coming soon? ;)

**Comment by asturur** [comment]
first thing i want to work on after release.

**Comment by asturur** [comment]
gradient changes will include just simple constructor, that coords system is a bit complicate to digest and i would like to add an angle property instead.
I m not sure if it will be a breaking change or just addition

**Comment by asturur** [comment]
released 2.0 rc 1

i changed the node code to be the same as browser code.
I know this is not a change supposed to be in beta -> rc transition, but node was broken and now works.

now createCanvasForNode(....) is no more required nor available. Just create a Canvas as normal
