### ISSUE TITLE
Blur on big scale rect

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4462]
## Version
2.0 beta

## Test Case
Kitchensink or anywhere.

## Steps to reproduce
Create a rect, scale it really big. Then take a look at the edges.

## Expected Behavior
Edges should be sharp (because it's just vector). 

## Actual Behavior
Edges are blurred. Look the boundaries of red rectangle are not sharp (rect is scaled 10x). Circle is ok because it's still scaled at 100% .
![capture d ecran 2017-11-16 a 09 02 14](https://user-images.githubusercontent.com/8090162/32880184-087848b2-caad-11e7-97ce-11541f2c7a54.png)

We really started to notice it (and becoming annoying) when we integrated a zoom into our app.

Any idea why? Is it cache related?

**Comment by asturur** [comment]
So there are parameters in the cache, explained in the apposite page to limit the cache size.
But those are triggered after 2Mpixel size. like 1000x2000 or something like that. does not look like you are at this size yet.

let me check it on kitchen sink

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/32896339-13342b1e-cae3-11e7-8f33-11ccf8ae96a1.png)

So i zoomed like 100X i get an object that is 5000x5000, cache limit kicks in before and i have a little blurry edge.
I disabled retina before doing this.

**Comment by blobinabottle** [comment]
Okay thanks for the clarification :-) 
And is it possible that the zoom level of the canvas play into the maths? Because in my test I have an object of 2000x1000px and if I zoom I get the blurry edge.

**Comment by asturur** [comment]
if you are zooming a 2000x1000 and also zoom the canvas yes, you go over the limit.
What objects have you? paths? rects?

So to be honest a rect should have always a sharp cache ( if cached )  and that may happen or not, i have to check. But then if it has let or top with 0.5, will be blurry and you can do little about it.

**Comment by blobinabottle** [comment]
It's rectangles. And canvas is zoomed x2. So as you say we are over the limit. 

But even on rounded position (10,10) it's blurred. Look here:
https://jsfiddle.net/mt96ko6g/4/ 
And turn on/off objectcaching you'll see huge difference, and the obj is just 2000x2000

**Comment by asturur** [comment]
Here you can see the cache images of 4 rects,

49x49 e 50x50 with and without strokeWidth of 1 pixel.
They are all sharp.

Then i zoomed a canvas the maximum i could, up to 1593x1593 canvas size.
The cache is still sharp apart from the inner border that cannot be fit on a pxel integer.

( conisdering that we have a 49px of width and 1+1 of stroke, it may happen that on 1500px cache you cannot mantain proportion since 1500 is not divisible by 51. )

All those things can be improved, in many ways it all depends how much code they requires.
Some step i can take:
1) remove the extra white border of the cache that is used for avoding the growth each scale step,  the extra transparent step is the one creating the blurriness, and that is the first thing i want to remove, that step should be removed when we are on minimum cache and maximum cache.

2) allora max cache canvas size as of now but with integer multiplication, that means stopping some pixel before the max but keeping integers.

not much else for now.

![download 2](https://user-images.githubusercontent.com/1194048/32972821-92e593a4-cbf4-11e7-91f0-11b920977a34.png)
![download 1](https://user-images.githubusercontent.com/1194048/32972822-930205f2-cbf4-11e7-8fd4-0fac8aacc9e4.png)
![download](https://user-images.githubusercontent.com/1194048/32972823-931e9604-cbf4-11e7-9c9e-d5fa453d980f.png)
![download 8](https://user-images.githubusercontent.com/1194048/32972824-9338ce0c-cbf4-11e7-8b62-34e06067b967.png)

![bigger](https://user-images.githubusercontent.com/1194048/32972820-92c35172-cbf4-11e7-873c-e9022352bf17.png)
![image](https://user-images.githubusercontent.com/1194048/32972870-ca69a022-cbf4-11e7-8fcd-5a6b32c0510e.png)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/32981762-4e35bc44-cc7a-11e7-9c4a-b9915d4a5394.png)

removing the white padding on the max size ( that was useless anyway ) the blurriness goes away!

**Comment by blobinabottle** [comment]
awesome!
