### ISSUE TITLE
Object selectable =  false, not working for active object

### ISSUE THREAD

**Issue by durga598** [kangax/fabric.js#4463]
## Version
2.0.0 beta 7

## Test Case
[jsFiddle](https://jsfiddle.net/durga598/h9kj1ksg)

## Steps to reproduce
Make canvas selection false and object selection false, Still active object is movable.
## Expected Behavior
In version 1.x it was not movable [jsFiddle](https://jsfiddle.net/durga598/h9kj1ksg/2/)
## Actual Behavior
Can able to move when canvas selection and object selection both are false.

This is in `mixins/canvas_events.mixin.js line 558`
If I add this, it works.
> if (target.selectable && target === this._activeObject && (target.__corner || !shouldGroup)) {

**Comment by asturur** [comment]
its ok.
a non selectable object can't be selected.
Does not mean that if is already selected can't be dragged at all.
You should set it as `evented: false` if you do not want it to react.

**Comment by Usman-Hassan-Gu** [comment]
How can i set the object evented to true if lets say it was false? I am trying to achieve a lock and unlock functionality for an object, but even when lockMovementX and Y to false and I set the hasControls to false and also set the selectable to false when I highlight multiple objects including the one I lock it becomes selectable and you can move it or scale it. I know this is obviously because it is part of an activeSelection but how can it not do that? And i think if i set evented to false, i can not change it back again to true because then i can no select the object. I know there is a solution to this and i can try to find a way but i don't know if there is something initially coded to fabric that i can use to achieve this.

**Comment by devniz** [comment]
@usmangurowa You don't want to set object.evented to false, otherwise, you'll lose all events and interactivity on that object. You can achieve a **lock/unlock** feature by manipulating only the movement and scaling properties of the object.

Here is a working example:

`  const toggleLock = () => {
    let obj = activeCanvas().getActiveObject();

    if (!isLocked) {
      // Lock the object's movement and scaling
      obj.lockMovementX = true;
      obj.lockMovementY = true;
      obj.lockScalingX = true;
      obj.lockScalingY = true;

      // Update the locked state variable
      isLocked = true;
    } else {
      // Unlock the object's movement and scaling
      obj.lockMovementX = false;
      obj.lockMovementY = false;
      obj.lockScalingX = false;
      obj.lockScalingY = false;

      // Update the locked state variable
      isLocked = false;
    }
  };`
