### ISSUE TITLE
Touch event select shape

### ISSUE THREAD

**Issue by Ronalses** [kangax/fabric.js#4528]
Hello, I would like to know which is the best way to get the elements when making touch on mobile.

This is the way I do it in desktop : https://jsfiddle.net/ronalses/zL7a0oxj/

But selecting them that way does not work well on mobile.

Thank you very much!

**Comment by Ronalses** [comment]
Try to create a pointer and detect the intercept but it does not work as expected, because it detects the bounding box. https://jsfiddle.net/ronalses/9mpeftvq/

Do you think you could eliminate the bounding box?
Although with the rectangle I also have the same problem.

**Comment by asturur** [comment]
can you explain better the problem?

**Comment by Ronalses** [comment]
I want to get the objects on mobile.
just like I click on desktop. Example: https://jsfiddle.net/ronalses/zL7a0oxj/

When I tap on objects in mobile, it is very difficult to obtain them.

Excuse my English.

Thanks for your help.

**Comment by asturur** [comment]
that is a problem small objects, small selection area, small screen, big fingers.
Nothing i can do about.

**Comment by Kampii** [comment]
I think @Ronalses is using perPixelTargetFind on desktop, but on mobile it gets tricky because it is hard to tap exactly on the line for example. [Here](http://fabricjs.com/intersection) is a nice  demo of intersection detection but intersection is checked against bounding boxes and not the actual shapes. If there was a way to merge the concept between perPixelTargetFind and intersectsWithObject, and have a method called something like perPixelIntesectsWithObject, then I think that would solve the problem? 

![image](https://user-images.githubusercontent.com/725316/33531311-15f3677e-d840-11e7-8a00-ef6f608dd74c.png)
