### ISSUE TITLE
Rounded width & height value (not really a bug I guess)

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4537]
## Version
2.0

## Test Case
https://jsfiddle.net/blobinabottle/ys7zLywu/9/

## Steps to reproduce
I try to get always rounded values for width & height, like they are on a pixel grid. But it seems whatever we do as long as there is decimal at play, we'll always get something like 400.0000001 (because binary system). 
But what's really weird is that the getBoundingRect give another width or height, something like 393 instead of 395. 

So basically I have three questions:
- how would you do it to get always perfect rounded width & height? 
- why getBoundingRect has this difference of 1 or 2? Why sometimes this value is not rounded while the calculated with or height actually are? 
- At the end how to be sure what size the shape really is? :-)

I can switch to Stackoverflow as it's probably not a bug, and maybe more related to javascript/binary shit, just tell me.

thanks

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

Read the description and tell me if it makes sense for you.

Also getBoundingRect is zoom and padding influenced, so if your zoom is not 1, will give a bigger or smaller size, inless you specify absolute=true in that case zoom and padding is ignored.

Being boundingRect aligned with the axis, if there is an angle the dimension changes too.

![image](https://user-images.githubusercontent.com/1194048/33741060-34fb2d3a-dba3-11e7-8a92-c42070f2d4ce.png)

the black box is the bounding rect.


for the 0.000001 factors that are the trigonometric functions in js, i think a bit we can fix it, not that much

**Comment by blobinabottle** [comment]
Thanks for the info. Didn't know about the padding.
But.... still it gives inconsistent results even with getBoundingRect(true) (scale*width = 200 and getBoundRect = 199 or 198)
But... results seems coherent with getBoundingRect(true, true)
Not sure why?

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

the second true, skip current .aCoords, .oCoords and just use the real numbers.
Is slower, takes in consideration your roundings.

If you do .setCoords() and you do not modify the object, then the function will give you same results with or without the second argument set to true.

If you can replicate an example of a case offsetting of significative decimal ( 0.001 is significative ) during getBoundingRect i will look into the possible bug, otherwise we should close this.

**Comment by blobinabottle** [comment]
Couldn't get such an offset. I think we can close this.
