### ISSUE TITLE
*Safari Only* Setting the height/width of a fabric.Image after using setElement with a canvas doesn't display the image.

### ISSUE THREAD

**Issue by dennisrjohn** [kangax/fabric.js#4542]
## Version
2.0.rc3

## Test Case
https://jsfiddle.net/kcr3tvuz/10/

## Steps to reproduce
1. Create a canvas and draw an image to it's context.
2. 2. Create a fabric.Image
3. Use setElement to set the canvas as the image element
4. Set the height and width of the image

## Expected Behavior
The image will draw on the canvas

## Actual Behavior
The image does not draw on the canvas

I'm not sure if this is actually worth fixing, as it's Safari only and can be worked around by setting the height and width of the fabric.Image before calling setElement. I'm logging it here in case anyone else runs into the issue.

**Comment by asturur** [comment]
I think the problem lies in that float values.
once set to floats, the real canvas dimensions are, logged in console:
![image](https://user-images.githubusercontent.com/1194048/33794369-3fdb2a7e-dccb-11e7-

99a3-079d770e2e9f.png)

The HTML specs for canvas asks for LONG to be used for width and height, i m not sure FLOATS are ok.

I would say that whatever works after setting floats to dimensions of an image, is a gift of some underlying rounding implementation.

Image.setElement reset the image width/height putting it to integer, wiping what ever you set before setElement.

When setting it back to floats after setElement you are asking drawImage to pickup fractions of pixels that do not exists.

Some browsers may tolerate it, other may not.
