### ISSUE TITLE
Automate package deployments via travis

### ISSUE THREAD

**Issue by jedateach** [kangax/fabric.js#4596]
I'm not sure why the `dist`, and `coverage` folders are in the git repo. I'm going to assume it is to do with wanting the project to be publishable to the npm registry, or some download location(s).

It is a hassle to work with `dist` always changing as the code is worked on. Every commit, in theory, should be including changes to `dist` files.
It is possible to distribute/package/release often without needing to commit these files into the codebase.

Travis can be configured to deploy every tag as a released package:
https://docs.travis-ci.com/user/deployment/npm/

**Comment by asturur** [comment]
Is an old setup.
I work with modern js tools since one year and half, and before i did not touch anything because i was scared to break something i did not see.

In the dist folder there is a built lib, a `.require` version that is mistery to me, a gizipped and a minified. Definitely too much.
The gizipped version and the minified version make the commits log horrible and this is why i avoid build them every time.

For version 2.0 UP i plan to update the version number often, as soon as a significant commit is done, other than the package, there is a changelog to update, a website and small stuff. So yes, i will research an automation process.

Any hint is welcome.

Also there is the long debate of the browser build, the gesture build, the smaller build.
Since fabricjs is modular ( and growing big in code size ) people wants the light - medium - heavy verison, ready in packages, thing i do not want to do at all. I was thinking to switch to publishing the broken files, with a postinstall script that builds it so that people can automate in their build chain their custom build.

I think cloudflare needs the built dist in order to mirror it on the cdn anyway

**Comment by jedateach** [comment]
Can you clarify what is done each time this project is published as a new version?
e.g.:

- Run build script
- Commit, tag, and push
- Publish on npm
- Something on cloudflare
- more?

I think a good goal is to automate every publishing step on every new tag, and possibly also on every commit to master (if that is considered a stable branch).

**Comment by jedateach** [comment]
Managing smaller build output is becoming easier with a technique called 'tree-shaking':
https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking
Note that requires the use of ES6 modules.

**Comment by asturur** [comment]
so when i decide is time for release:

npm run build
npm run test
npm run export_dist_to_site  // useless in travis but i need to do it
npm run export_tests_to_site // useless in travis but has to be done
update changelog.md
// on fabricjs.com repo
node build_docs.js
update the changelog post, explain what is new
check the visual regression test
//on github.com
update the changelog page
tag a new release and edit the release comment
npm publish


Master is the only stable branch.

The steps that consume more time are the changelog update, and this is done manually because tools that work on commit messages works bad ( and i do terrible commit messages )

What i would like to achieve is tag, publish  each commit, provided i can add visual regression tests. This will give me more confidence i m not breaking anything and should give also more confidence to people using the library.

Another topic would be the removal of the dist folder from the github.
Building, uglifying and publish to npm could be automated with travis, but there are jsfiddle outside that are based on the master version of the built lib, also cloudfare from my understanding is like configured to come here and pick up the tagged version and host it ( i do not even know where the config is, probably kangax knows )

**Comment by asturur** [comment]
With all the things i have to do and want to do ES6 is not an option now.
Would require a transpiling step, also most of the devs that use fabricjs just include it in a page with a script tag and move on, i do not want to make things more complicated.
