### ISSUE TITLE
toDataURL: multiplier : 1 BUG

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#4617]
## Version
2.0

## Test Case
none

## Steps to reproduce
Useing Retina Screen and  Canvas.enableRetinaScaling is `true`

useing `toDataURL` 

options is
```Javascript
canvasObject.toDataURL({
  multiplier: 1
})
```

is  2x size bigger than Normal screen image

but I am try this:

```Javascript
canvasObject.toDataURL({
  multiplier: 0.5
})
```
It is work .

```Javascript
canvasObject.toDataURL({
  multiplier: 0.9999999999
})
```
also work very well

**Comment by asturur** [comment]
Hey @evolutionjay i would like to fix this, are you able to making a failing fiddle? Reading the code i cannot understand why it should happen.

**Comment by dmitry-kostin** [comment]
bump also have this issue on retina screen
created the fiddle https://jsfiddle.net/Lktr6jL0/

**Comment by asturur** [comment]
thanks!

**Comment by dmitry-kostin** [comment]
@asturur Could you confirm please can this be fixed anytime soon? Or should we start to search the solution by owns?

**Comment by asturur** [comment]
so i do not think there is any strange bug. retina canvas are double big.
Probably we should take care of this when exporting, but this is the default behaviour and has been like this since version 1.5, an 2.0 is in rc status.
What i can do is address with docs, if you do not want retina scaling on exported image use:

{ multiplier: 1/canvas.getRetinaScaling() }

changing code would not give you any difference that you cannot obtain like this

**Comment by asturur** [comment]
Ok since for object we offer an option, default to false, we can extend the same on the canvas.
