### ISSUE TITLE
Long text is blur

### ISSUE THREAD

**Issue by HATyCEHKA** [kangax/fabric.js#4663]
Long text is blur. 
https://jsfiddle.net/ngqz7yss/3/
![image](https://user-images.githubusercontent.com/26141774/35683118-07248ab2-0774-11e8-9596-cf3627df8ecb.png)

Moreover the longer the text is, the more blur it is.
https://jsfiddle.net/ngqz7yss/2/
![image](https://user-images.githubusercontent.com/26141774/35683127-0dc3be9c-0774-11e8-875e-9a65cbdd506d.png)

## Version
2.0.0

**Comment by jfgouda** [comment]
Not sure of the cause, but disabling objectCaching fixed the issue. 
See the following: https://jsfiddle.net/jgouda/cgpj428e/

**Comment by asturur** [comment]
@HATyCEHKA i l try to explain you the best i can.

The text object you create on one line is long: 15844 pixels.
Biggest canvas support i have ever seen is firefox at 16k.
The text is cached on single surface that is big in your case: 4096 because is the maximum allowed by fabricJS.
So your text is exactly 4 : 1 with pixel needed, is blurried.

If you want to traget ONLY firefox and chrome you can push up the max size of the cache to 12.000 and it will bi less blurry, but still not perfect, and performances will be horrifing.

In those cases, if really long strings are needed, the best thing to do is disable caching.

FabricJS does the best i can in displaying good graphic at reasonable speed, but sizes bigger than 4k x 4k, so 16Mega Pixel per single object, makes the browser crawl.

It mostly depend from your use case. How many object you need to handle?
