### ISSUE TITLE
loadFromJSON causes loss of clipping areas on objects

### ISSUE THREAD

**Issue by kuzmicz** [kangax/fabric.js#4722]
## Version
1.7.22
2.0.1

### 2.0.1
https://jsbin.com/wawimimulo/1/edit?html,js,output
### 1.7.22
https://jsbin.com/rowihelome/1/edit?html,js,output 

## Steps to reproduce
1. Create main clipping area eg. Rect.
2. Create an other clipping object (Path) inside this clipping area (created rect).
3. Convert canvas to json.
4. Try to load saved JSON to canvas.

## Expected Behavior
After reloading image should be clipped into circle shape.

## Actual Behavior
Image appearing outside the clipping circle after reloading objects by toJSON and loadFromJSON method.

**Comment by asturur** [comment]
This is why clipTo is deprecated. Is hard to use and does not play well with the other features.

To make it work you have to declare your clipping area inside the clipTo function.

**Comment by contact2mayurkukadiya** [comment]
I have also same issue. I have implement whole functionality in my large scaled project. but when I use loadFromJSON() function, I was shocked, that fabric old version not support re-cliping when canvas load from JSON.

Is there any solution for resolve this issue in old version ? because I can't convert my whole project into new version for now.

**Comment by asturur** [comment]
Well is a javascript problem.
Your clipTo function has to use only local variables, or it has to take them from window and you have to be sure that they are defined when you go to re-enlive the function.
