### ISSUE TITLE
BUG when creating image from SVG file in fabric v2 – image is cropped and doesn't match the one passed to fabric.Image

### ISSUE THREAD

**Issue by dmitry-kostin** [kangax/fabric.js#4783]
Something with image size broken, image is cropped and don't match actual image size

## Version
2.1

## Test Case
https://jsfiddle.net/iwooky/qgtobju7/64/

## Steps to reproduce
1. take any svg file, eg: I used this one:
https://www.dropbox.com/s/z4l2vfxtts8w0e7/flower.svg?dl=0
2. upload it with example fiddle – check the results
3. change fabric version to 1.7 - just uncomment v1.7 script in fidde then repeat the step 2 and compare results again

## Expected Behavior
In v2 its supposed to work as in 1.7 i guess

## Actual Behavior
in v2 image is getting cropped

actual result in v2: https://www.dropbox.com/s/6rm3owahg1gs9pa/Screenshot%202018-03-05%2015.48.45.png?dl=0
actual result in v1.7: https://www.dropbox.com/s/zifkk4mgvlglxhr/Screenshot%202018-03-05%2015.49.39.png?dl=0

**Comment by dmitry-kostin** [comment]
@asturur could you check this please?

**Comment by scriptspry** [comment]
Setting `width="512px" height="512px"` to the svg tag in file.svg restored expected behaviour.

In this case, since the svg image didn't specify any width and height.. The width and height of the canvas seem to be inherited by the image for it's width and height attributes.

I don't know exactly what the underlying issue is, but I think #4733 may be related here.

**Comment by dmitry-kostin** [comment]
@scriptspry 
ya may be setting width/height explicitly may resolve this issue, but i have dynamic canvas size via canvas.setWidth/Height ¯\_(ツ)_/¯
I have to rollback to older version until this is resolved

**Comment by salomonsanz** [comment]
@asturur please check this, this is very important to fix for people that wants to migrate from v1 to v2

**Comment by asturur** [comment]
This is a well known problem with svg that do not specify image width and height.
The spec says that they are big 100% of the container ( in the dom ) not having a container available, width and height can be chosen with freedom by the browser developers since spec do not specify.

In this case the browser set as naturalWidth/naturalHeight 150 ( completely random values ) and the canvas.drawImage native function when used in the 9 arguments version, it fails miserably.

I tried to explain to chrome people that this is wrong, but they say that being undefined, is ok.

look safari:
![image](https://user-images.githubusercontent.com/1194048/38168053-8e04549e-3542-11e8-832a-fb59ba218040.png)


probably ie11 looks good too.

Sadly you have to use svgs that specify the right width/height.

I could add a boolean to draw the image with the 5 argument version, that works a little bit better, but to me looks like we are trying to fix broken specs and broken decisions in browsers in the wrong place.
