### ISSUE TITLE
Filters is not working when image is inside an group.

### ISSUE THREAD

**Issue by CrackerakiUA** [kangax/fabric.js#4813]
## Version
1.7.22

## Test Case
http://jsfiddle.net/rok1yupd/10/

## Steps to reproduce
When I apply filter to an image which is inside an group, that filter is not taking place directly, only when i save that image and loadFromJson the saved data.

## Expected Behavior
Filters to apply directly.

## Actual Behavior
Filters show up only when I do loadFromJson

**Comment by asturur** [comment]
After you apply a filter, set the image as dirty, so the group knows that he has to rerender.
This could be handled a fabricLevel too anyway.

**Comment by CrackerakiUA** [comment]
dirty is simply ```oImg.dirty = true;``` ?
here it's not working http://jsfiddle.net/rok1yupd/15/

**Comment by scriptspry** [comment]
Setting the group as dirty seems to do the job.

Also another underlying issue here is that the filtering was not working because of CORS and tainting of the canvas on loading img from external domain.

Using imageOpts for the fabric.Image.fromURL fixed the CORS issue.

Working fiddle: http://jsfiddle.net/rok1yupd/23/

**Comment by CrackerakiUA** [comment]
@scriptspry thank you

**Comment by asturur** [comment]
img.set('dirty', true) is going to update the group to dirty automatically.
