### ISSUE TITLE
Image rotation issue

### ISSUE THREAD

**Issue by dczii** [kangax/fabric.js#4851]
I have no problem adding an image in the canvas but whenever I try to rotate the image the rotation point is correct but the image is a bit odd. after rotating it will go back to normal but in the rotated selection. The only problem is when rotating.

Here is the screenshot while rotating
![screen shot 2018-03-19 at 11 34 03 am](https://user-images.githubusercontent.com/6244798/37576904-b4221a0e-2b69-11e8-9a67-c3f5325b7d31.png)

Below screenshot is the image after rotating.
![screen shot 2018-03-19 at 11 37 49 am](https://user-images.githubusercontent.com/6244798/37576949-fa8ca87e-2b69-11e8-8f04-b261a67a500e.png)

Here is a working [JSFIDDLE](https://jsfiddle.net/dczii/aehLfaps/) to replicate the issue

**Comment by asturur** [comment]
When an object is rotated, top and left are moved to the center.
do not use .top and .left directly but try to use `object._getLeftTopCoords`  if you need the top,left while rotating.

Other than that, this is more an help request rather than a bug/feature. So please continue on stackoverflow is more help is needed

**Comment by rodriggochaves** [comment]
Hi! Can this method be listed here? [here](http://fabricjs.com/docs/fabric.Object.html)?
