### ISSUE TITLE
fabric.PatternBrush difference between drawing mode and resulting fabric.Object

### ISSUE THREAD

**Issue by Kienz** [kangax/fabric.js#851]
If you draw a `fabric.PatternBrush` the result during the drawing mode is different to to the created `fabric.Path`.
You can see this in kitchensink demo - draw one dot (before testing update fabric - see ba2a0e6dff36beb7afb7417c63090604338c87ac).

In drawing mode:
![image](https://f.cloud.github.com/assets/954545/1151018/044d81a8-1ef4-11e3-809a-696cc44c9d87.png)

After drawing mode (fabric.Path):
![image](https://f.cloud.github.com/assets/954545/1151022/0c9b2d60-1ef4-11e3-8cbd-ddfbbc8466f7.png)

**Comment by asturur** [comment]
it think that in renderStroke we are missing the counterpart of this part of  renderFill function:

```
if (this.fill.toLive) {
        ctx.translate(
          -this.width / 2 + this.fill.offsetX || 0,
          -this.height / 2 + this.fill.offsetY || 0);
      }
}
```

**Comment by asturur** [comment]
Ok i found the problem:
The pattern brush has the pattern always aligned to 0,0.
So when we draw it the pattern is not translated.

When the object is actually created, we always do some translation of canvas to place it properly.
I tried to do a ctx.translate for widht/2 and left in all possible combination and permutation, but i did not get any good result.

I think anyway this is the problem.

I was thinking about do the correct translation just in the path _render function, because this problem is tied mainly to drawing mode that produces path, is not a general rule of our rendering pipeline.
